### ISSUE TITLE
kml output doesn't show uav data

### ISSUE THREAD

**Issue by idogreenfeld** [auvsi-suas/interop#101]
For some reason when exporting data to kml i cant see the uav's path (import to google earth).
I can see that the data exists by going into the django administration under uas telemetry and I can also see the plane moving on the server while in flight.

Also the data i'm getting in the CSV file doesn't look correct

Am i doing something wrong?

**Comment by prattmic** [comment]
The KML export excludes admin/superusers (e.g., testadmin). Are you uploading data as a regular user? https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/views/auvsi_admin/export_kml.py#L25

**Comment by idogreenfeld** [comment]
I'm uploading as a regular user.
Another weird thing is that i tried using the live kml view and when using it i can indeed see my uav displayed on the map.

can you please upload an example of how the CSV file should look? i'm worried that something went wrong during the installation of the server and that's why i get all of these weird behaviours.

**Comment by prattmic** [comment]
My guess is that you are missing takeoff and landing events. The live KML is fairly lenient; it will more or less display whatever data is sent to the server. The export KML, on the other hand, is more strict. Each user is expected to have TakeoffOrLandingEvents denoting when they were flying. The export KML only includes data from "flights" (time spans when the TakeoffOrLandingEvents indicate the team was flying).

I suspect this is your problem with the CSV as well. It is going to be looking at data from when the team is flying.

Unfortunately, some of this "admin" functionality is very well documented. At the moment, you need to go into the Django admin interface (`/admin`) to manually create TakeoffOrLandingEvents. @pmtischler is working on an interface to make creating these events simpler.

**Comment by pmtischler** [comment]
Yup, our documentation on how to do this properly isn't great- and it'd be better if the interface just walked you through it. #37 is tracking this work- but we won't likely get to it until after this year's competition.

**Comment by idogreenfeld** [comment]
that did the trick! thanks!
