### ISSUE TITLE
Release Docker Containers as Default Deployment

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#103]
Similar to Vagrant, to decrease time for teams to start using interop.
https://docs.travis-ci.com/user/docker/

**Comment by prattmic** [comment]
+1 I've considered this as well.

**Comment by pmtischler** [comment]
Useful for Django:
https://docs.docker.com/compose/django/

**Comment by marcoflowers** [comment]
Hey our team is using this currently for docker support. Even though it doesn't split out the database it works.

FROM ubuntu:14.04
WORKDIR /app
RUN apt-get update && apt-get install -y git wget apt-transport-https
RUN cd /app && git clone https://github.com/auvsi-suas/interop
RUN cd /app/interop/setup && bash setup.sh

Issues:
Have to run these on start of the container
service postgresql start
service apache2 restart

When writing to postgres you must sleep a bit if you are trying to create a new image with the data in postgres.

**Comment by marcoflowers** [comment]
Yea here is a full docker file that should work.

FROM ubuntu:14.04
WORKDIR /app
RUN apt-get update && apt-get install -y git wget apt-transport-https
RUN cd /app && git clone https://github.com/auvsi-suas/interop
RUN cd /app/interop/setup && bash setup.sh
CMD service postgresql start && service apache2 restart && bash

Run the first command in the same folder as the Dockerfile.
docker build -t auvsi-suas/interop .
docker run  -it -p 9050:80 auvsi-suas/interop

It will be running on localhost:9050(takes a bit to start up).

You could host the image on https://hub.docker.com/ and could upload an updated image on every push to master with Travis https://docs.travis-ci.com/user/docker/.

**Comment by pmtischler** [comment]
This is coming along. The PR is getting quite large. To make our use of Docker an effective development workflow I've needed to change many things (e.g. remove Puppet). It's looking good though. My remaining tasks:
* Require mounted volume to easily get access to logs and maintain DB between runs
* Register & setup Dockerhub, setup Travis testing and push of images
* Update a lot of documentation
