### ISSUE TITLE
no module named interop

### ISSUE THREAD

**Issue by rishabh750** [auvsi-suas/interop#104]
while running python clientproxy.py i'm getting no module named interop error. although i have created and added the path of interop repository in PYTHONPATH variable.but still getting an error.
Here's the link to the output of cmd on windows :- http://pastebin.com/3P6Uu81c

**Comment by akashcas** [comment]
I would suggest that you should check out your python folder and make sure that you know actually where all the modules are stored and do the needful ( it Is just the hint ).

**Comment by prattmic** [comment]
Your PYTHONPATH should include the path to `interop/client/` not just the root of the interop repo. Or you should be in the client virtualenv that contains the module and its dependencies.
