### ISSUE TITLE
Sending data to server after reset causes error

### ISSUE THREAD

**Issue by DarkmatterVale** [auvsi-suas/interop#105]
Hi,

If I attempt to send data using the included MissionPlanner (and client proxy) script without first loading data into the database, it does not work. Am I doing something wrong or is it alright that I am loading test data into the database?

The code that causes the error:
```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py flush
$ python manage.py syncdb
$ deactivate
```

Doesn't cause the error:

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py flush
$ python manage.py syncdb
$ python manage.py loaddata fixtures/test_fixture.yaml
$ deactivate
```

**Comment by prattmic** [comment]
This is expected. There must be a valid MissionConfig before data can be sent to the server. The test fixture includes a simple one. You may create a more complex one if you like.

http://auvsi-suas-competition-interoperability-system.readthedocs.org/en/latest/management/configure_manage.html#create-a-missionconfig

**Comment by DarkmatterVale** [comment]
Thank you!
