### ISSUE TITLE
Setup.sh upgrades packages without user permission

### ISSUE THREAD

**Issue by legonigel** [auvsi-suas/interop#114]
As the title says, when I run `upgrade.sh` it upgrades packages on my system without my permission by running `apt-get upgrade`. A script should not upgrade my packages without my permission because upgrade packages can, in cases where packages are not held back correctly, break software. 

If a specific version of a package is required, it should be specified in the `apt-get install` as `apt-get install package=version`.

**Comment by prattmic** [comment]
This is a very reasonable complaint. I'm not going to change the setup system at this point, but we will consider this after competition.
