### ISSUE TITLE
Uploaded target images not found

### ISSUE THREAD

**Issue by idogreenfeld** [auvsi-suas/interop#129]
Hi,

I'm trying to upload the identified targets to the interop server.
I can upload all of the targets and their details and i can also upload a thumbnail.

On the server I can see the targets and their details but when I try and open the thumbnail image I get a "Not Found Error"

See the attached pictures - 

![screenshot from 2016-06-03 17_27_59](https://cloud.githubusercontent.com/assets/15867904/15781883/ca43d064-29b0-11e6-97de-64b6440a82ed.png)
![screenshot from 2016-06-03 17_28_19](https://cloud.githubusercontent.com/assets/15867904/15781884/ca653c72-29b0-11e6-91d2-b4745e72e2a4.png)

Any assistance would great!

Thanks, Ido

**Comment by prattmic** [comment]
Have you tried uploading a target image using the official API?
(/api/targets/{id}/image)?

**Comment by idogreenfeld** [comment]
yes.... that's what i did

**Comment by pmtischler** [comment]
The error isn't with the supported API, it's with the admin interface which
blocks such requests when not in Debug mode.

**Comment by pmtischler** [comment]
To clarify, Django blocks the interface because it doesn't have ACL
checking. Our supported interface does. Either use the supported interface
or enable Debug mode. You can also review targets via the admin display
under Mission > Review Targets.

**Comment by idogreenfeld** [comment]
For some reason I see a "Review Targets" option under mission... do I need to be connected to the server while doing it?

**Comment by pmtischler** [comment]
I'm not understanding the question.

**Comment by idogreenfeld** [comment]
Sorry, I ment I don't see the "Review Targets" option under Mission... only Team Evaluation...
Do I need to be connected to the server or can I do it when I'm offline after the targets have been uploaded?

**Comment by pmtischler** [comment]
You need to update to the latest code.

**Comment by idogreenfeld** [comment]
OK, I'll try it... thanks!
