### ISSUE TITLE
Create mission config without targets

### ISSUE THREAD

**Issue by idogreenfeld** [auvsi-suas/interop#130]
Hi,

When i try to create a new mission config, I'm asked to insert a target manually.
This causes a problem later on when i try to upload my own targets via interop since the server already has a target which wasn't uploaded by my system and so i try to overwrite it.

To be more precise, say i'm uploading my first target - my program will thing it's the first target on the server and will try to upload it's picture to the 1st target - i will then get a server error saying i can't overwrite the first target since it wasn't created by me.

Is there a way of creating a mission without inserting a manual target?

Thanks

**Comment by pmtischler** [comment]
You are misusing the API. You first create a target with a POST request.
The request will come back with the ID of the target you created. If you
forget the ID, you can do a GET request to get all IDs owned by you. You
can then do a PUT or DELETE to update your target and image as desired.
It's not valid to assume you're first target will have ID 1.

Look at the tool we provide to upload targets from the other format. That
provides a working example of how to do this correctly.

**Comment by idogreenfeld** [comment]
thanks for the help
