### ISSUE TITLE
Poor synced-folder performance with Vagrant

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#14]
[This documentation](https://docs.vagrantup.com/v2/synced-folders/virtualbox.html) says that using Virtualbox default synced folders has a bug with `sendfile` (not fixed since 2011), and that we should either disable it or switch to either NFS (only non-windows), SMB (only windows), or rsync (syncs on vagrant up, vagrant reload, and manually). The docs for [EnableSendfile Off](http://httpd.apache.org/docs/2.2/mod/core.html#enablesendfile) seem to imply it would just be a potential performance penalty.

`sendfile` is used for static assets and on target data. I haven't noticed an issue yet, maybe it's a non-issue.

**Comment by pmtischler** [comment]
@prattmic Any status on this?

**Comment by prattmic** [comment]
No updates.

**Comment by pmtischler** [comment]
I think it's out of scope for us to fix this. Closing.
