### ISSUE TITLE
Add consistent caching via separate process

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#143]
E.g. memcached

This will reduce cross process inconsistencies during invalidation on a change.

**Comment by prattmic** [comment]
Hashing and invalidation of what? The few things we cache in the server?

**Comment by pmtischler** [comment]
Yes, like obstacle configuration used for spline generation.

**Comment by pmtischler** [comment]
Oh I also forgot. We can use the consistent hashing to do things like last position for a team, or whether the team is active.

**Comment by pmtischler** [comment]
Realizing I was for some reason using consistent "hashing" where I meant consistent "caching". My mind must have leaked thoughts from a different project. Sorry about that.
