### ISSUE TITLE
Productionize integration with MissionPlanner

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#146]
It's clear we need to start solving some of this for teams.

Smart client. Client side dedupe and validation, rate reporting, status reporting, etc.

Display integration. Show obstacles for SDA.

**Comment by pmtischler** [comment]
Also look into where telemetry bottleneck and for upstream fix.

**Comment by prattmic** [comment]
I'm not sure that showing SDA is an important feature for us to be working on. Otherwise, I agree.

**Comment by pmtischler** [comment]
I'm going to look into it. If it's reasonable I'll give it a go.
