### ISSUE TITLE
Show telemetry data in admin overview

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#147]
Mostly a display change.

**Comment by prattmic** [comment]
Specifically, showing current upload rate would be helpful.

**Comment by pmtischler** [comment]
I've been trying to find a good way to monitor this type of application. Afaict there isn't a good way to monitor Django apps using multiprocess Apache. My best guess is a push mechanism to a known port that then exports this info. Thoughts?

**Comment by prattmic** [comment]
It seems to me that the simplest way would simply be to have `/api/teams` include their 5-10s moving average update rate.
