### ISSUE TITLE
Insufficient cache invalidation

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#162]
## Problem 1: Invalidation on Model Save

We register a handler on certain model saves to invalidate the cache:
https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/views/clear_cache.py#L33

If you edit a model that is not in that list, the cache will not get invalidated. For example, a GPS position change underneath an obstacle's waypoint won't cause the cached obstacle to be invalidated. We can't simply add GPS to the list because telemetry upload, which comes at 10Hz+, would invalidate it constantly. Some options:

* Use a cache clear handler when the edge case is a problem (what we have now; unclean)
* Change the model structure so the cache handler can do it properly (ideal; could create model uncleanliness)
* Touch the obstacle on an underlying waypoint change (flaky; unclean)
* Have a custom REST interface which does the right thing (clean; larger surface area; planned anyway)

## Problem 2: Serving & Test Requests Share Same Cache & Keyspace

The test code creates a separate database table, and cleans it up on test destruction. The test runner has been changed to clear the cache on test environment setup and destruction. However, external code like the client tests still need to use the cache invalidation request. I'm not sure how much time it's worth trying to solve this part.

**Comment by prattmic** [comment]
I understand Problem 1. That comes from manual edits made in the admin interface.

I don't understand Problem 2. How does a user of the API manage to get the cache into an invalid state? Why can't the views ensure that never happens.

**Comment by pmtischler** [comment]
For example, say you run the test and then make a request to `/api/obstacles`. The value will be that which was generated by the test, rather than what's currently in the database. The view code shouldn't react to whether it's a test, but the test should do the right thing. I think the following line might be sufficient to handle problem 2:
https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/test_runner.py#L45

**Comment by pmtischler** [comment]
Per offline conversation, I think Problem 1 will be handled separately with our custom REST interface, and Problem 2 is fine for now.
