### ISSUE TITLE
Make latest telemetry queries more efficient

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#164]
We hit a scalability problem with latest queries for telemetry. @prattmic improved the db query substantially, which will help us survive. We can use the now consistent cache to store the result of "latest" queries, like latest telemetry for each user.

**Comment by pmtischler** [comment]
@prattmic Instead of modifying the telemetry interface, what do you think about editing the team interface? It already queries for all active team telemetry using a timestamp filter on all telemetry.
https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/models/access_log.py#L60

**Comment by prattmic** [comment]
Do you mean using that DB query to determine if the team is active, plus returning it to the caller, thus saving an extra query?

That will help, but I'm not sure it will be enough.

**Comment by pmtischler** [comment]
I didn't fully explain :( 

I'm thinking of having a function `users_active` which returns a map from `user` to `latest`, where `latest` is `None` if the user is not active and the last log otherwise. This would cause 2N queries (per team one to determine active, one to determine telemetry) to become 1 with some python-level filtering.
