### ISSUE TITLE
Docker Build Failing

### ISSUE THREAD

**Issue by phoenix1796** [auvsi-suas/interop#210]
While building the docker image on Docker-1.12-3 on Fedora24(x64) in initial data load step , django fails to initialize , stating that : "db is starting up" 
But , the db successfully started just before it .

After a bit of digging , I found this [article](http://postgresql.nabble.com/FATAL-the-database-system-is-starting-up-td4941646.html) which suggests to add a few flags to postgresql at startup , I tried adding these in postgresql.conf but the options are not recognized in that file.

UPDATE : I managed to get the server running in the docker image by using sleep 100 after the db startup command which effectively stalls the build by 100 seconds , this works , but it would be better if we could solve the problem instead of using this hack-ish method .

![StackTrace](https://cloud.githubusercontent.com/assets/9111802/20235154/92c03e8c-a8b0-11e6-8ea1-57e41fd914c4.png)
![Full Output](https://cloud.githubusercontent.com/assets/9111802/20235155/92c50e80-a8b0-11e6-8dba-dd9f33e7f8c0.png)

**Comment by pmtischler** [comment]
You shouldn't be solving this problem at all. The benefit of us using Docker is you **don't** need to build the docker image. If you followed the [instructions](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html) you would have download our prebuilt and pretested docker image and just run it.
