### ISSUE TITLE
auvsi_mp.py global variable `sent_since_print` not brought into scope

### ISSUE THREAD

**Issue by oneTimePad** [auvsi-suas/interop#215]
Hello,

I noticed when testing `interop/client/missionplanner/auvsi_mp.py` that in the function `handle_upload_result` the global variable `sent_since_print` is not being brought into scope (i.e. `global sent_since_print`). Thus `handle_upload_result` is creating a new local variable on each call `sent_since_print`. I tested this with python2.7.12 on ArchLinux.

**Comment by pmtischler** [comment]
Deduping with #209 which is tracking various problems with the script.
