### ISSUE TITLE
Error: pg_config executable not found

### ISSUE THREAD

**Issue by jburgin** [auvsi-suas/interop#221]
After following the steps in the getting started for setting up the interop server, I would get `Error: pg_config executable not found` when running setup_tools.sh. I rectified the problem by manually installing `libpq-dev` which includes pg_config but just wanted to let you know in case it should be installed as part of the script but is not actually getting installed.

**Comment by pmtischler** [comment]
That's odd. We run setup_tools.sh as [part of Travis testing](https://github.com/auvsi-suas/interop/blob/master/.travis.yml#L10) and it doesn't have a problem. We definitely use Postgres, but we install the python-psycopg2 package which should add its dependencies. 

Can you link your setup log?

**Comment by jburgin** [comment]
Here is the log for setup_docker.sh: https://drive.google.com/open?id=0B--7hhyE8c36RGZ6Y2E5djdTVk0

Here is the log for setup_tools.sh before I installed libpq-dev: https://drive.google.com/open?id=0B--7hhyE8c36ZUZrbjl2bWVtdUE

Log for setup_tools.sh after installing libpq-dev: https://drive.google.com/open?id=0B--7hhyE8c36bnpBWjRxNnhVaEk

I am running a fresh install of Ubuntu 16.04 LTS 64 bit

**Comment by pmtischler** [comment]
Fixed via [6e1cf99](https://github.com/auvsi-suas/interop/commit/6e1cf9995cda451106d31d96595758a643559fcb).
