### ISSUE TITLE
pyOpenssl

### ISSUE THREAD

**Issue by parvu** [auvsi-suas/interop#226]
please advise on correcting error on executing setup_tools.sh:
    creating build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
    build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-NblUsw/cryptography/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-PmONdW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-NblUsw/cryptography/

**Comment by pmtischler** [comment]
Please post the setup log.

**Comment by pmtischler** [comment]
Actually, there isn't a reason to use `setup_tools.sh`. That is for developers mostly- I've updated the getting started documentation.

**Comment by parvu** [comment]
hello
I have attached the log

On Sat, Mar 11, 2017 at 10:42 PM, Phillip Tischler <notifications@github.com
> wrote:

> Please post the setup log.
>

**Comment by parvu** [comment]
please help. I can't connect to server:
- ping works:
> ping 10.10.130.2
PING 10.10.130.2 (10.10.130.2) 56(84) bytes of data.
64 bytes from 10.10.130.2: icmp_seq=1 ttl=64 time=0.119 ms
64 bytes from 10.10.130.2: icmp_seq=2 ttl=64 time=0.085 ms
64 bytes from 10.10.130.2: icmp_seq=3 ttl=64 time=0.085 ms
64 bytes from 10.10.130.2: icmp_seq=4 ttl=64 time=0.112 ms
^C
- but connection refused:
(venv2)root@c5e4ba2e3a7c:/interop/client# ./tools/interop_cli.py --url
http://10.10.130.2:8000 --username testuser missions
Interoperability Password:
2017-03-11 20:47:08,475: urllib3.connectionpool: INFO: Starting new HTTP
connection (1): 10.10.130.2
Traceback (most recent call last):
  File "./tools/interop_cli.py", line 156, in <module>
    main()
  File "./tools/interop_cli.py", line 151, in main
    client = Client(args.url, args.username, password)
  File "/interop/client/interop/client.py", line 52, in __init__
    'password': password})
  File "/interop/client/interop/client.py", line 79, in post
    r = self.session.post(self.url + uri, timeout=self.timeout, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 497,
in post
    return self.request('POST', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455,
in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558,
in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378,
in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.10.130.2',
port=8000): Max retries exceeded with url: /api/login (Caused by <class
'socket.error'>: [Errno 111] Connection refused)
I user password: testpass
and I see errors in server log:

root@d857a5a5370d:/interop/server# cd /var/log/apache2
root@d857a5a5370d:/var/log/apache2# cat interop_server_error.log
[Thu Mar 09 13:08:26.325212 2017] [:error] [pid 101:tid 139824894605184]
mod_wsgi (pid=101): Target WSGI script '/interop/server/server/wsgi.py'
cannot be loaded as Python module.
[Thu Mar 09 13:08:26.325275 2017] [:error] [pid 101:tid 139824894605184]
mod_wsgi (pid=101): Exception occurred processing WSGI script
'/interop/server/server/wsgi.py'.
[Thu Mar 09 13:08:26.325313 2017] [:error] [pid 101:tid 139824894605184]
Traceback (most recent call last):
[Thu Mar 09 13:08:26.325345 2017] [:error] [pid 101:tid 139824894605184]
File "/interop/server/server/wsgi.py", line 28, in <module>
[Thu Mar 09 13:08:26.325442 2017] [:error] [pid 101:tid 139824894605184]
  Client().get("/")
[Thu Mar 09 13:08:26.325460 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
500, in get
[Thu Mar 09 13:08:26.325727 2017] [:error] [pid 101:tid 139824894605184]
  **extra)
[Thu Mar 09 13:08:26.325746 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
303, in get
[Thu Mar 09 13:08:26.325778 2017] [:error] [pid 101:tid 139824894605184]
  return self.generic('GET', path, secure=secure, **r)
[Thu Mar 09 13:08:26.325792 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
379, in generic
[Thu Mar 09 13:08:26.325817 2017] [:error] [pid 101:tid 139824894605184]
  return self.request(**r)
[Thu Mar 09 13:08:26.325830 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
448, in request
[Thu Mar 09 13:08:26.325855 2017] [:error] [pid 101:tid 139824894605184]
  response = self.handler(environ)
[Thu Mar 09 13:08:26.325868 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
109, in __call__
[Thu Mar 09 13:08:26.325892 2017] [:error] [pid 101:tid 139824894605184]
  self.load_middleware()
[Thu Mar 09 13:08:26.325905 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py",
line 50, in load_middleware
[Thu Mar 09 13:08:26.326051 2017] [:error] [pid 101:tid 139824894605184]
  mw_class = import_string(middleware_path)
[Thu Mar 09 13:08:26.326071 2017] [:error] [pid 101:tid 139824894605184]
File
"/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py",
line 26, in import_string
[Thu Mar 09 13:08:26.326180 2017] [:error] [pid 101:tid 139824894605184]
  module = import_module(module_path)
[Thu Mar 09 13:08:26.326195 2017] [:error] [pid 101:tid 139824894605184]
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Mar 09 13:08:26.326264 2017] [:error] [pid 101:tid 139824894605184]
  __import__(name)
[Thu Mar 09 13:08:26.326290 2017] [:error] [pid 101:tid 139824894605184]
ImportError: No module named middleware
[Thu Mar 09 13:08:26.332995 2017] [:error] [pid 102:tid 139824894605184]
mod_wsgi (pid=102): Target WSGI script '/interop/server/server/wsgi.py'
cannot be loaded as Python module.
[Thu Mar 09 13:08:26.333033 2017] [:error] [pid 102:tid 139824894605184]
mod_wsgi (pid=102): Exception occurred processing WSGI script
'/interop/server/server/wsgi.py'.
[Thu Mar 09 13:08:26.333069 2017] [:error] [pid 102:tid 139824894605184]
Traceback (most recent call last):
[Thu Mar 09 13:08:26.333098 2017] [:error] [pid 102:tid 139824894605184]
File "/interop/server/server/wsgi.py", line 28, in <module>
[Thu Mar 09 13:08:26.333189 2017] [:error] [pid 102:tid 139824894605184]
  Client().get("/")
[Thu Mar 09 13:08:26.333207 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
500, in get
[Thu Mar 09 13:08:26.333448 2017] [:error] [pid 102:tid 139824894605184]
  **extra)
[Thu Mar 09 13:08:26.333469 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
303, in get
[Thu Mar 09 13:08:26.333500 2017] [:error] [pid 102:tid 139824894605184]
  return self.generic('GET', path, secure=secure, **r)
[Thu Mar 09 13:08:26.333524 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
379, in generic
[Thu Mar 09 13:08:26.333550 2017] [:error] [pid 102:tid 139824894605184]
  return self.request(**r)
[Thu Mar 09 13:08:26.333562 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
448, in request
[Thu Mar 09 13:08:26.333585 2017] [:error] [pid 102:tid 139824894605184]
  response = self.handler(environ)
[Thu Mar 09 13:08:26.333596 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
109, in __call__
[Thu Mar 09 13:08:26.333620 2017] [:error] [pid 102:tid 139824894605184]
  self.load_middleware()
[Thu Mar 09 13:08:26.333631 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py",
line 50, in load_middleware
[Thu Mar 09 13:08:26.333791 2017] [:error] [pid 102:tid 139824894605184]
  mw_class = import_string(middleware_path)
[Thu Mar 09 13:08:26.333810 2017] [:error] [pid 102:tid 139824894605184]
File
"/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py",
line 26, in import_string
[Thu Mar 09 13:08:26.333915 2017] [:error] [pid 102:tid 139824894605184]
  module = import_module(module_path)
[Thu Mar 09 13:08:26.333932 2017] [:error] [pid 102:tid 139824894605184]
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Mar 09 13:08:26.333997 2017] [:error] [pid 102:tid 139824894605184]
  __import__(name)
[Thu Mar 09 13:08:26.334023 2017] [:error] [pid 102:tid 139824894605184]
ImportError: No module named middleware
[Thu Mar 09 13:08:26.338042 2017] [:error] [pid 100:tid 139824894605184]
mod_wsgi (pid=100): Target WSGI script '/interop/server/server/wsgi.py'
cannot be loaded as Python module.
[Thu Mar 09 13:08:26.338077 2017] [:error] [pid 100:tid 139824894605184]
mod_wsgi (pid=100): Exception occurred processing WSGI script
'/interop/server/server/wsgi.py'.
[Thu Mar 09 13:08:26.338114 2017] [:error] [pid 100:tid 139824894605184]
Traceback (most recent call last):
[Thu Mar 09 13:08:26.338140 2017] [:error] [pid 100:tid 139824894605184]
File "/interop/server/server/wsgi.py", line 28, in <module>
[Thu Mar 09 13:08:26.338238 2017] [:error] [pid 100:tid 139824894605184]
  Client().get("/")
[Thu Mar 09 13:08:26.338256 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
500, in get
[Thu Mar 09 13:08:26.338503 2017] [:error] [pid 100:tid 139824894605184]
  **extra)
[Thu Mar 09 13:08:26.338522 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
303, in get
[Thu Mar 09 13:08:26.338553 2017] [:error] [pid 100:tid 139824894605184]
  return self.generic('GET', path, secure=secure, **r)
[Thu Mar 09 13:08:26.338566 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
379, in generic
[Thu Mar 09 13:08:26.338591 2017] [:error] [pid 100:tid 139824894605184]
  return self.request(**r)
[Thu Mar 09 13:08:26.338603 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
448, in request
[Thu Mar 09 13:08:26.338628 2017] [:error] [pid 100:tid 139824894605184]
  response = self.handler(environ)
[Thu Mar 09 13:08:26.338641 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
109, in __call__
[Thu Mar 09 13:08:26.338664 2017] [:error] [pid 100:tid 139824894605184]
  self.load_middleware()
[Thu Mar 09 13:08:26.338676 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py",
line 50, in load_middleware
[Thu Mar 09 13:08:26.338822 2017] [:error] [pid 100:tid 139824894605184]
  mw_class = import_string(middleware_path)
[Thu Mar 09 13:08:26.338850 2017] [:error] [pid 100:tid 139824894605184]
File
"/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py",
line 26, in import_string
[Thu Mar 09 13:08:26.338962 2017] [:error] [pid 100:tid 139824894605184]
  module = import_module(module_path)
[Thu Mar 09 13:08:26.338979 2017] [:error] [pid 100:tid 139824894605184]
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Mar 09 13:08:26.339045 2017] [:error] [pid 100:tid 139824894605184]
  __import__(name)
[Thu Mar 09 13:08:26.339071 2017] [:error] [pid 100:tid 139824894605184]
ImportError: No module named middleware
[Thu Mar 09 13:08:26.344081 2017] [:error] [pid 99:tid 139824894605184]
mod_wsgi (pid=99): Target WSGI script '/interop/server/server/wsgi.py'
cannot be loaded as Python module.
[Thu Mar 09 13:08:26.344101 2017] [:error] [pid 99:tid 139824894605184]
mod_wsgi (pid=99): Exception occurred processing WSGI script
'/interop/server/server/wsgi.py'.
[Thu Mar 09 13:08:26.344152 2017] [:error] [pid 99:tid 139824894605184]
Traceback (most recent call last):
[Thu Mar 09 13:08:26.344181 2017] [:error] [pid 99:tid 139824894605184]
File "/interop/server/server/wsgi.py", line 28, in <module>
[Thu Mar 09 13:08:26.344255 2017] [:error] [pid 99:tid 139824894605184]
Client().get("/")
[Thu Mar 09 13:08:26.344267 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
500, in get
[Thu Mar 09 13:08:26.344421 2017] [:error] [pid 99:tid 139824894605184]
**extra)
[Thu Mar 09 13:08:26.344433 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
303, in get
[Thu Mar 09 13:08:26.344452 2017] [:error] [pid 99:tid 139824894605184]
return self.generic('GET', path, secure=secure, **r)
[Thu Mar 09 13:08:26.344458 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
379, in generic
[Thu Mar 09 13:08:26.344470 2017] [:error] [pid 99:tid 139824894605184]
return self.request(**r)
[Thu Mar 09 13:08:26.344475 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
448, in request
[Thu Mar 09 13:08:26.344486 2017] [:error] [pid 99:tid 139824894605184]
response = self.handler(environ)
[Thu Mar 09 13:08:26.344492 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/test/client.py", line
109, in __call__
[Thu Mar 09 13:08:26.344503 2017] [:error] [pid 99:tid 139824894605184]
self.load_middleware()
[Thu Mar 09 13:08:26.344509 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py",
line 50, in load_middleware
[Thu Mar 09 13:08:26.344598 2017] [:error] [pid 99:tid 139824894605184]
mw_class = import_string(middleware_path)
[Thu Mar 09 13:08:26.344609 2017] [:error] [pid 99:tid 139824894605184]
File
"/usr/local/lib/python2.7/dist-packages/django/utils/module_loading.py",
line 26, in import_string
[Thu Mar 09 13:08:26.344669 2017] [:error] [pid 99:tid 139824894605184]
module = import_module(module_path)
[Thu Mar 09 13:08:26.344678 2017] [:error] [pid 99:tid 139824894605184]
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Thu Mar 09 13:08:26.344722 2017] [:error] [pid 99:tid 139824894605184]
__import__(name)
[Thu Mar 09 13:08:26.344739 2017] [:error] [pid 99:tid 139824894605184]
ImportError: No module named middleware
[Sat Mar 11 18:20:46.368299 2017] [:error] [pid 109:tid 140386141714176]
2017-03-11 18:20:46,368 WARNING base Not Found: /favicon.ico
[Sat Mar 11 18:20:46.368417 2017] [:error] [pid 109:tid 140386141714176]
2017-03-11 18:20:46,368 WARNING base Not Found: /favicon.ico
[Sat Mar 11 18:20:46.371108 2017] [:error] [pid 109:tid 140386141714176]
2017-03-11 18:20:46,370 WARNING middleware [404] /favicon.ico (0.0030s)
[Sat Mar 11 18:20:46.371157 2017] [:error] [pid 109:tid 140386141714176]
<WSGIRequest: GET '/favicon.ico'>
[Sat Mar 11 18:20:46.371166 2017] [:error] [pid 109:tid 140386141714176] ===
[Sat Mar 11 18:20:46.371172 2017] [:error] [pid 109:tid 140386141714176]
Content-Type: text/html\r
[Sat Mar 11 18:20:46.371178 2017] [:error] [pid 109:tid 140386141714176] \r
[Sat Mar 11 18:20:46.371185 2017] [:error] [pid 109:tid 140386141714176]
<h1>Not Found</h1><p>The requested URL /favicon.ico was not found on this
server.</p>
[Sat Mar 11 18:37:24.103381 2017] [:error] [pid 124:tid 139875342751488]
2017-03-11 18:37:24,103 WARNING base Not Found: /favicon.ico
[Sat Mar 11 18:37:24.137061 2017] [:error] [pid 124:tid 139875342751488]
2017-03-11 18:37:24,103 WARNING base Not Found: /favicon.ico
[Sat Mar 11 18:37:24.141291 2017] [:error] [pid 124:tid 139875342751488]
2017-03-11 18:37:24,141 WARNING middleware [404] /favicon.ico (0.0383s)
[Sat Mar 11 18:37:24.141321 2017] [:error] [pid 124:tid 139875342751488]
<WSGIRequest: GET '/favicon.ico'>
[Sat Mar 11 18:37:24.141326 2017] [:error] [pid 124:tid 139875342751488] ===
[Sat Mar 11 18:37:24.141331 2017] [:error] [pid 124:tid 139875342751488]
Content-Type: text/html\r
[Sat Mar 11 18:37:24.141335 2017] [:error] [pid 124:tid 139875342751488] \r
[Sat Mar 11 18:37:24.141339 2017] [:error] [pid 124:tid 139875342751488]
<h1>Not Found</h1><p>The requested URL /favicon.ico was not found on this
server.</p>
[Sat Mar 11 19:40:28.563448 2017] [:error] [pid 115:tid 140619396511488]
2017-03-11 19:40:28,563 WARNING base Not Found: /favicon.ico
[Sat Mar 11 19:40:28.576302 2017] [:error] [pid 115:tid 140619396511488]
2017-03-11 19:40:28,563 WARNING base Not Found: /favicon.ico
[Sat Mar 11 19:40:28.586298 2017] [:error] [pid 115:tid 140619396511488]
2017-03-11 19:40:28,586 WARNING middleware [404] /favicon.ico (0.0233s)
[Sat Mar 11 19:40:28.586339 2017] [:error] [pid 115:tid 140619396511488]
<WSGIRequest: GET '/favicon.ico'>
[Sat Mar 11 19:40:28.586344 2017] [:error] [pid 115:tid 140619396511488] ===
[Sat Mar 11 19:40:28.586348 2017] [:error] [pid 115:tid 140619396511488]
Content-Type: text/html\r
[Sat Mar 11 19:40:28.586352 2017] [:error] [pid 115:tid 140619396511488] \r
[Sat Mar 11 19:40:28.586355 2017] [:error] [pid 115:tid 140619396511488]
<h1>Not Found</h1><p>The requested URL /favicon.ico was not found on this
server.</p>
[Sat Mar 11 20:36:52.259799 2017] [:error] [pid 113:tid 140619404904192]
2017-03-11 20:36:52,259 WARNING base Not Found: /favicon.ico
[Sat Mar 11 20:36:52.259909 2017] [:error] [pid 113:tid 140619404904192]
2017-03-11 20:36:52,259 WARNING base Not Found: /favicon.ico
[Sat Mar 11 20:36:52.262329 2017] [:error] [pid 113:tid 140619404904192]
2017-03-11 20:36:52,262 WARNING middleware [404] /favicon.ico (0.0030s)
[Sat Mar 11 20:36:52.262476 2017] [:error] [pid 113:tid 140619404904192]
<WSGIRequest: GET '/favicon.ico'>
[Sat Mar 11 20:36:52.262492 2017] [:error] [pid 113:tid 140619404904192] ===
[Sat Mar 11 20:36:52.262504 2017] [:error] [pid 113:tid 140619404904192]
Content-Type: text/html\r
[Sat Mar 11 20:36:52.262514 2017] [:error] [pid 113:tid 140619404904192] \r
[Sat Mar 11 20:36:52.262524 2017] [:error] [pid 113:tid 140619404904192]
<h1>Not Found</h1><p>The requested URL /favicon.ico was not found on this
server.</p>
[Sat Mar 11 21:12:59.010314 2017] [:error] [pid 113:tid 140619396511488]
2017-03-11 21:12:59,010 WARNING base Not Found: /api/client
[Sat Mar 11 21:12:59.010405 2017] [:error] [pid 113:tid 140619396511488]
2017-03-11 21:12:59,010 WARNING base Not Found: /api/client
[Sat Mar 11 21:12:59.011496 2017] [:error] [pid 113:tid 140619396511488]
2017-03-11 21:12:59,011 WARNING middleware [404] /api/client (0.0014s)
[Sat Mar 11 21:12:59.011512 2017] [:error] [pid 113:tid 140619396511488]
<WSGIRequest: GET '/api/client'>
[Sat Mar 11 21:12:59.011516 2017] [:error] [pid 113:tid 140619396511488] ===
[Sat Mar 11 21:12:59.011520 2017] [:error] [pid 113:tid 140619396511488]
Content-Type: text/html\r
[Sat Mar 11 21:12:59.011523 2017] [:error] [pid 113:tid 140619396511488] \r
[Sat Mar 11 21:12:59.011580 2017] [:error] [pid 113:tid 140619396511488]
<h1>Not Found</h1><p>The requested URL /api/client was not found on this
server.</p>
[Sat Mar 11 21:30:44.499411 2017] [:error] [pid 113:tid 140619421689600]
2017-03-11 21:30:44,499 WARNING base Not Found: /favicon.ico
[Sat Mar 11 21:30:44.500572 2017] [:error] [pid 113:tid 140619421689600]
2017-03-11 21:30:44,499 WARNING base Not Found: /favicon.ico
[Sat Mar 11 21:30:44.502158 2017] [:error] [pid 113:tid 140619421689600]
2017-03-11 21:30:44,501 WARNING middleware [404] /favicon.ico (0.0032s)
[Sat Mar 11 21:30:44.502189 2017] [:error] [pid 113:tid 140619421689600]
<WSGIRequest: GET '/favicon.ico'>
[Sat Mar 11 21:30:44.502193 2017] [:error] [pid 113:tid 140619421689600] ===
[Sat Mar 11 21:30:44.502196 2017] [:error] [pid 113:tid 140619421689600]
Content-Type: text/html\r
[Sat Mar 11 21:30:44.502199 2017] [:error] [pid 113:tid 140619421689600] \r
[Sat Mar 11 21:30:44.502202 2017] [:error] [pid 113:tid 140619421689600]
<h1>Not Found</h1><p>The requested URL /favicon.ico was not found on this
server.</p>




On Sat, Mar 11, 2017 at 10:42 PM, Phillip Tischler <notifications@github.com
> wrote:

> Please post the setup log.
>

**Comment by parvu** [comment]
Solved connection problem with:

 

./tools/interop_cli.py --url http://10.10.130.1:8000 --username testuser missions

 

seems it was due to the way docker is masqurading.

 

Thank you
