### ISSUE TITLE
SQL connection pooling 

### ISSUE THREAD

**Issue by idogreenfeld** [auvsi-suas/interop#23]
hello,

in our interoperability implementation we constantly open and close 3 requests to the server - one for telemetry, one for obstacles and one for server info.
after getting the required data from each request we close the stream and the request itself.

we've noticed that every once in a while we get an error from the server saying "Fatal: sorry too many clients already"
after looking into the server we realized that even tough our requests are being closed on our end, they are being pooled on the server's end.
the server has a limit of 100 connections, and if the pooled requests on the server aren't being closed fast enough we get the error.

will the server in the competition have more connections? or will the pooling be disabled?

thanks in advance
ido

**Comment by pmtischler** [comment]
As per the Implementation Hints Point 1, you should not create a new connection for each set of requests. Unless the connection is broken (e.g. temporary error like cable was unplugged), you should open only a single connection for the entire mission. See the provided sample client implementation.
http://auvsi-suas-competition-interoperability-system.readthedocs.org/en/latest/integration/hints.html
https://github.com/auvsi-suas/interop/blob/master/client/interop/client.py

Django applies connection pooling per thread. It maintains the connection until CONN_MAX_AGE expires. Our setup uses 24 threads (4 processes with 6 threads each), so it should only create 24 connections at any one time. However, if the development server is used, it creates a new connection for each request and doesn't do connection pooling, and subsequently can hit the 100 connection limit if accessed too fast.
https://github.com/auvsi-suas/interop/blob/master/server/server/settings.py#L75
https://github.com/auvsi-suas/interop/blob/master/setup/puppet_files/auvsi_suas/manifests/apache_setup.pp#L53
https://docs.djangoproject.com/en/1.9/ref/databases/#caveats

As described in System Management, you shouldn't use the Development Server unless you are developing or debugging the implementation. To verify system performance (e.g. verify 10Hz), you should use the standard setup with Apache on a dedicated machine.
http://auvsi-suas-competition-interoperability-system.readthedocs.org/en/latest/management/start_stop.html

**Comment by idogreenfeld** [comment]
great, thanks for the help!
