### ISSUE TITLE
akashcas@ - Python 2/3 tests failing

### ISSUE THREAD

**Issue by akashcas** [auvsi-suas/interop#24]
I git pulled the most recent changes. I then created a new vagrant machine, ran vagrant setup for automated setup . The Python2 and python 3  test failed. [Output](http://pastebin.com/QXnxa5Aq)

**Comment by prattmic** [comment]
Could you please post the contents of `/var/log/apache2/interop_server_access.log` and `/var/log/apache2/interop_server_error.log`? They should contain more details about the server error.

**Comment by pmtischler** [comment]
@akashcas Any update?

**Comment by akashcas** [comment]
@pmtischler @prattmic I overcame that error by doing the complete manual setup using setup.sh . All the test ran successfully for the first time but later i ran the test.sh for the same again it gave me the same error . Sorry late reply as i was out of station.

**Comment by akashcas** [comment]
Why i am getting the same error when i am running the test again after once it showed me all successful in earlier case .

**Comment by prattmic** [comment]
I'm not sure, could you please post the contents of the files I mentioned the previous time you had trouble: `/var/log/apache2/interop_server_access.log` and `/var/log/apache2/interop_server_error.log`?

**Comment by akashcas** [comment]
interop_server_access.log : 

```
127.0.0.1 - - [27/Jan/2016:18:47:30 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "GET /api/obstacles HTTP/1.1" 200 196 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "GET /api/obstacles HTTP/1.1" 200 195 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "GET /api/server_info HTTP/1.1" 200 128 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "GET /api/server_info HTTP/1.1" 200 128 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:31 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/telemetry HTTP/1.1" 400 59 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/telemetry HTTP/1.1" 400 59 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/telemetry HTTP/1.1" 200 34 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/telemetry HTTP/1.1" 200 34 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 400 20 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 400 20 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:32 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "GET /api/obstacles HTTP/1.1" 200 195 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "GET /api/obstacles HTTP/1.1" 200 195 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "GET /api/server_info HTTP/1.1" 200 128 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "GET /api/server_info HTTP/1.1" 200 129 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:34 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/telemetry HTTP/1.1" 400 59 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/telemetry HTTP/1.1" 400 59 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/telemetry HTTP/1.1" 200 34 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/telemetry HTTP/1.1" 200 34 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/login HTTP/1.1" 400 20 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/login HTTP/1.1" 400 20 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
127.0.0.1 - - [27/Jan/2016:18:47:35 +0530] "POST /api/login HTTP/1.1" 200 17 "-" "python-requests/2.9.1"
```
interop_server_error.log : 

```
[Wed Jan 27 18:27:09.500271 2016] [mpm_worker:notice] [pid 1484:tid 139899453327232] AH00292: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Wed Jan 27 18:27:09.500318 2016] [core:notice] [pid 1484:tid 139899453327232] AH00094: Command line: '/usr/sbin/apache2'
[Wed Jan 27 18:45:21.935374 2016] [mpm_worker:notice] [pid 1484:tid 139899453327232] AH00295: caught SIGTERM, shutting down
[Wed Jan 27 18:45:22.685129 2016] [mpm_worker:notice] [pid 2978:tid 139763358717824] AH00292: Apache/2.4.7 (Ubuntu) mod_wsgi/3.4 Python/2.7.6 configured -- resuming normal operations
[Wed Jan 27 18:45:22.685292 2016] [core:notice] [pid 2978:tid 139763358717824] AH00094: Command line: '/usr/sbin/apache2'

```

**Comment by prattmic** [comment]
Odd, the logs don't show any 500 errors, which the test showed it was getting. Can you clear those file out, then rerun the tests? Afterwards there should be only relevant logs in the files.

**Comment by pmtischler** [comment]
@akashcas Please do a Git pull to get the latest code. We've recently submitted some fixes and better logging. Then re-run the setup and post that log here (w/ pastebin), re-run the tests and post that log here too.

**Comment by akashcas** [comment]
@pmtischler @prattmic  sorry i m out of my state due to some family problem .Will get back to you in a week . Sorry

**Comment by vtgist** [comment]
Hey, strangely enough, I had the same issues too.
Git pulled the latest changes as of around 3 days back, and I'm arriving at the same errors as well.

Server error log:
[http://pastebin.com/W0mkfkyw]

Access error log:
[http://pastebin.com/S0nR7ebA]

Have re-setup using setup.sh multiple times, (doing a clean wipe of all the installed software each time) and there doesn't seem to be any difference, please advise?

**Comment by pmtischler** [comment]
Please post the setup log as well.

**Comment by vtgist** [comment]
Setup log:
[http://pastebin.com/LKctTuNM]

Extremely sorry for the delay.

**Comment by vtgist** [comment]
I tried setting up Vagrant to get it to run there, but I encountered some errors there too.
Here's the setup log for the Vagrant setup.

http://pastebin.com/0HwS4szF

**Comment by pmtischler** [comment]
The setup log shows failures which caused it to skip the rest of the setup- no surprise it isn't working. 

In the first log file it says the command timed out. In the second it says this command returned an error:

```
Error: /Stage[main]/Auvsi_suas::Server_install/Exec[karma and jasmine]/returns: change from notrun to 0 failed: npm install --force -g karma karma-jasmine karma-chrome-launcher phantomjs karma-phantomjs-launcher karma-cli returned 255 instead of one of [0]
```

I ran a Vagrant setup on a new VM and got the same error. Executing the command manually within the Vagrant VM gave me the error it needed to be run as root. Re-running with root caused the command to succeed with status 0. The `puppet apply` executes it as root. Adding `sudo` to the puppet module didn't help either. Running the setup on my host machine succeeded.

@prattmic Just a heads-up, I'm also getting `pip` errrors.

Travis is continually setting up and testing and hasn't had any problems. It doesn't test Vagrant however. @prattmic Shall we add Vagrant setup to Travis CI?

**Comment by pmtischler** [comment]
Nevermind about the `pip` errors, I believe it was just `venv` clobbering due to synced folders.

**Comment by pmtischler** [comment]
@prattmic Are these errors expected?

```
Error: /interop/client/venv3/bin/pip wheel --help > /dev/null 2>&1 && { /interop/client/venv3/bin/pip wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { /interop/client/venv3/bin/pip --log /interop/client/venv3/pip.log install --upgrade $wheel_support_flag   -e  /interop/client || /interop/client/venv3/bin/pip --log /interop/client/venv3/pip.log install --upgrade   -e  /interop/client ;} returned 1 instead of one of [0]
Error: /Stage[main]/Auvsi_suas::Client_install/Python::Pip[interop3]/Exec[pip_install_interop3]/returns: change from notrun to 0 failed: /interop/client/venv3/bin/pip wheel --help > /dev/null 2>&1 && { /interop/client/venv3/bin/pip wheel --version > /dev/null 2>&1 || wheel_support_flag='--no-use-wheel'; } ; { /interop/client/venv3/bin/pip --log /interop/client/venv3/pip.log install --upgrade $wheel_support_flag   -e  /interop/client || /interop/client/venv3/bin/pip --log /interop/client/venv3/pip.log install --upgrade   -e  /interop/client ;} returned 1 instead of one of [0]
```

**Comment by pmtischler** [comment]
As per comment on PR: Vagrant can't be tested in Travis.

**Comment by prattmic** [comment]
Re: https://github.com/auvsi-suas/interop/issues/24#issuecomment-183836745: The issue seems to be that, as @pmtischler said the `karma` install timed out. This may have simply been due to a slow network connection? I was not aware, but that Puppet command has a default timeout of 5 minutes.

Re: https://github.com/auvsi-suas/interop/issues/24#issuecomment-184303438: No, those errors aren't expected. Looking at the backtraces in context, it looks like `/interop` is not writable by the default user. This could be due to an odd combination of permissions on the host synced folder and guest synced folder.

**Comment by prattmic** [comment]
@vtgist: Inside the VM (`vagrant ssh`), could you run and post the output of `ls -l /` and `ls -l /interop`?

**Comment by vtgist** [comment]
Hey,

Contents of "ls -l" inside the VM:

drwxrwxr-x 1 vagrant vagrant 4096 Feb 13 12:28 interop

Contents of "ls-l /interop":

drwxrwxr-x 1 vagrant vagrant  4096 Feb 13 12:41 client
-rw-rw-r-- 1 vagrant vagrant   595 Feb 13 11:50 CONTRIBUTING.md
drwxrwxr-x 1 vagrant vagrant  4096 Feb 13 11:50 data
drwxrwxr-x 1 vagrant vagrant  4096 Feb 13 12:36 docs
-rw-rw-r-- 1 vagrant vagrant 11325 Feb 13 11:50 LICENSE
-rw-rw-r-- 1 vagrant vagrant  1633 Feb 13 11:50 README.md
drwxrwxr-x 1 vagrant vagrant  4096 Feb 14 11:12 server
drwxrwxr-x 1 vagrant vagrant  4096 Feb 14 13:21 setup
-rwxrwxr-x 1 vagrant vagrant  1385 Feb 13 11:50 test.sh
drwxr-xr-x 1 vagrant vagrant  4096 Feb 13 13:35 tmp
drwxrwxr-x 1 vagrant vagrant  4096 Feb 13 11:50 tools

**Comment by vtgist** [comment]
Also, we saw that the karma module hadn't been installed. So we did a package-by-package installation of all pre-requisites, at which point the Javascript Frontend test passed. The initial server test passes as well. But the Python2/Python3 test still fails. I installed it on my teammate's system with pretty much the same results.

**Comment by vtgist** [comment]
Another thing. In the setup.sh file it says that some of the dependencies are installed in that specific order because there are conflicts, but the setup stops when it encounters the installation of those dependencies. Here's the setup log for that (done on a clean machine)

http://pastebin.com/vQrvpxuk

**Comment by justineaster** [comment]
Also having python 2 and 3 failing.
setup: http://pastebin.com/DVc7kGps
test: http://pastebin.com/4YWD0qzk

**Comment by prattmic** [comment]
@justineaster You seem to be having a different issue. All of your failures are due to time outs. What hardware are you running on. It seems like your machine is very slow.

**Comment by prattmic** [comment]
@vtgist I think that last error may have been a transient error as some of the Puppet modules had new version uploaded. Let us know if you get the same error again.

The permissions on `/interop` look correct. Could you try `mkdir /interop/tmp/npm-19143-Wq2CcxBw` and verify that it does not return an error?

Also, please try a fresh install (`vagrant destroy`/`vagrant up`). I'd like to see if you are reliably getting the same errors.

**Comment by vtgist** [comment]
Okay, this is weird. This is what I got when destroyed vagrant and ran it again:


Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'ubuntu/trusty64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2222 (adapter 1)
[default] -- 80 => 8000 (adapter 1)
[default] -- 8080 => 8080 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period. This can
mean a number of things.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

My network connection is working fine. My system is pretty fast too.

**Comment by vtgist** [comment]
Regarding the new Puppet modules:


**Puppet module "puppetlabs-concat" already installed
Notice: Preparing to upgrade 'puppetlabs-concat' ...
Notice: Found 'puppetlabs-concat' (v1.2.5) in /etc/puppet/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not upgrade module 'puppetlabs-concat' (v1.2.5 -> latest)
  There are 1 newer versions
    No combination of dependency upgrades would satisfy all dependencies
    Dependencies will not be automatically upgraded across major versions
    Upgrading one or more of these modules may permit the upgrade to succeed:
    - puppetlabs-stdlib
    Use `puppet module upgrade --force` to upgrade only this module**

When I tried to manually force the upgrade, it did upgrade the module, but the normal 
'puppet module upgrade' command installs it in /.puppet/modules instead of the /etc/puppet/modules like the setup.sh file does.

**Comment by vtgist** [comment]
So I edited the setup.sh file and included --force in the 'puppet module upgrade' command and that seemed to install everything. This is the setup log from that instance:

http://pastebin.com/t17AW0Dp

This still doesn't solve the python2/python3 test failing though. Ran test.sh again.

**Comment by vtgist** [comment]
This is the error I got on the mkdir command inside the VM.

**mkdir: cannot create directory ‘/interop/tmp/npm-19143-Wq2CcxBw’: Protocol error**

**Comment by prattmic** [comment]
It sounds like the filesystem errors are related to restrictive permissions
on the host folder. Perhaps try setting full permissions on the host folder.

It also sounds like this is more of a problem on a Windows host. If you are
on Windows it may be worth trying a Linux host.

**Comment by vtgist** [comment]
I'm running this entirely on a Linux machine. I got pretty much the same errors outside the VM as well.

**Comment by vtgist** [comment]
This is the test log for the dedicated machine. All the dependencies installed properly now. Any idea why the python test is still messing up?

http://pastebin.com/bZxtiEge

**Comment by prattmic** [comment]
It sounds like the web server on the machine is very slow or not running.
Can you browse to http://localhost on the machine (or run 'curl
http://localhost')?

**Comment by vtgist** [comment]
Might be so. I tried both. The webpage doesn't load, and the curl command doesn't return anything, i.e the command doesn't even exit. 

But if I go over to localhost:8000 I get a rudimentary version of the website without any CSS or functionality.

**Comment by prattmic** [comment]
I am a bit confused. On a dedicated machine, there should not be a server on port 8000. You aren't manually starting a server with `manage.py` are you? Does the Apache log contain any information?

**Comment by vtgist** [comment]
Alright so I reinstalled Ubuntu on my system, and now it seems to pass all the tests. I would love to post why it didn't work earlier, but I have absolutely no clue.

**Comment by prattmic** [comment]
Hurray! I am sorry you had such a hard time getting things working and that we couldn't help more, but I'm glad it is finally working,
