### ISSUE TITLE
Interop server does not return "Set-Cookie" header

### ISSUE THREAD

**Issue by GGJesus** [auvsi-suas/interop#240]
Hi,

Part of our team is currently working on a SDA (Sense, Detect, and Avoid) viewer to visualize the location of the drone, obstacles, and other points relevant in the competition. To achieve this, we're using an HTML file with the Leaflet JS library imported (with offline tiles) and adding markers and lines to the map to visualize the information.

In order to get the data for the map, we load in all the geo points for home, waypoints, and etc. except the drone's current position (such as lat, long, alt, and dir since it's not provided by the server) from the Interop. server.

**We can log into the Interop. server, however, we are not receiving the Set-Cookie header**, and without this header, we cannot load in the mission data as it requires the `sessionid` from the cookie.

We attempt to login in using Javascript with the JQuery 3.1.1 library. Here is the relevant code:
```
var interopEndpointURL = "http://" + $("#address").val() + ":8000/" + $("#endpointURL").val);

$.ajax({
    method: "POST", type: "POST", // redundancy
    url: (interopEndpointURL + "login"),

    async: true,
    cache: false,
    crossDomain: true,
    
    data: {"username": $("#username").val(), "password": $("#password").val()},

    contentType: "application/json", dataType: "json"

    statusCode: {
        400: function(textStatus) {
            alert(textStatus.responseText);
        }
    }
})
```
*Additionally,* I use an extension in Chrome to bypass Cross Origin Control errors.

This is the full connection inspection in Chrome, with the request and response's headers and data.

![capture](https://cloud.githubusercontent.com/assets/6162516/24838086/05cd7afc-1d0f-11e7-93e7-8c73a4aec7ef.PNG)

**As you can see, no cookie was returned by the Interop server despite the server returning a 200 OK http status code.** [According to the Interop specification,](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/specification.html#post--api-login) a Set-Cookie header should have been returned, along with the 200 OK.

This the details of the our setup:

| Name | Version | For |
| :----- | :------- | :-- |
| JQuery | 3.1.1 | Javascript library to communicate between browser and Interop server. |
| Chrome | 57.0.2987.133 (64-bit) | Web browser. |
| Apache | 2.4 (64-bit) | Local web server to serve viewer and map tiles. | 
| Windows 10 | OS Build 14393.969 | Operating system. |

I'm opening this issue because there is no other resource that I can consult to fix this problem.

[There was another issue opened about cookies,](https://github.com/auvsi-suas/interop/issues/91) however, it is specifically inquiring about how cookies are handled between the Interop server and the provided client.

After reviewing the code that was provided the in the issue referenced above, it _appears_ that no cookie is set by the server, and if it is, it's not immediately obvious where.

Any help would be greatly appreciated,
James.

**Comment by pmtischler** [comment]
```
$ curl -v --data "username=testuser&password=testpass" http://localhost:8000/api/login
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/login HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Length: 35
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 35 out of 35 bytes
< HTTP/1.1 200 OK
< Date: Sun, 09 Apr 2017 15:23:00 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Vary: Cookie
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: sessionid=f0bbqjr3cmz300qpv9s1q99g2jkyguxy; expires=Sun, 23-Apr-2017 15:23:00 GMT; httponly; Max-Age=1209600; Path=/
< Content-Length: 17
< Content-Type: text/html; charset=utf-8
< 
* Connection #0 to host localhost left intact
```

As you can see, the server is setting `Set-Cooke` with `sessionid`. Our Python client library also uses these cookies as part of the session, and we have CI testing that.

We don't debug team's implementations, so closing this as I've verified the server is doing the right thing.

I'd recommend performing interop requests at your web server, rather than at the client. That is, instead of:
`Team Server <-> Team Chrome Browser <-> Interop Server`
Do this:
`Interop Server <-> Team Server <-> Team Chrome Browser`

**Comment by GGJesus** [comment]
Hi @pmtischler ,

Thanks for your quick response!

I took your recommendation and curl'd the Interop server that we're running and I got almost an identical response:

```
C:\Users\Robotics\Desktop\curl>curl.exe -v --data "username=[REDACTED]&password=[REDACTED]" http://10.10.130.2:8000/
*   Trying 10.10.130.2...
* TCP_NODELAY set
* Connected to 10.10.130.2 (10.10.130.2) port 8000 (#0)
> POST / HTTP/1.1
> Host: 10.10.130.2:8000
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Length: 34
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 34 out of 34 bytes
< HTTP/1.1 302 FOUND
< Date: Sun, 09 Apr 2017 16:50:17 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Vary: Cookie
< X-Frame-Options: SAMEORIGIN
< Location: http://10.10.130.2:8000/admin/login/?next=/
< Content-Length: 0
< Content-Type: text/html; charset=utf-8
<
* Connection #0 to host 10.10.130.2 left intact
```

**It still does not return the cookie.**

I noticed that it returned the "Vary: Cookie" header, [indicating that the server requires the cookie header in future requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Vary), however it has not returned an initial cookie.

**Comment by pmtischler** [comment]
You used the wrong URL in that last test. You used `/`, and got a redirection (302) to `/admin/login`. That is, you requested the admin homepage and got a redirect to the admin login.

**Comment by GGJesus** [comment]
@pmtischler , you were right:

```
C:\Users\Robotics\Desktop\curl>curl.exe -v --data "username=[REDACTED]&password=[REDACTED]" http://10.10.130.2:8000/api/login
*   Trying 10.10.130.2...
* TCP_NODELAY set
* Connected to 10.10.130.2 (10.10.130.2) port 8000 (#0)
> POST /api/login HTTP/1.1
> Host: 10.10.130.2:8000
> User-Agent: curl/7.53.1
> Accept: */*
> Content-Length: 34
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 34 out of 34 bytes
< HTTP/1.1 200 OK
< Date: Sun, 09 Apr 2017 17:31:58 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Vary: Cookie
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: sessionid=8i83vo82qza0mql2foboiayklproebla; expires=Sun, 23-Apr-2017 17:31:58 GMT; httponly; Max-Age=1209600; Path=/
< Content-Length: 17
< Content-Type: text/html; charset=utf-8
<
Login Successful.* Connection #0 to host 10.10.130.2 left intact
```

**The server does return a Set-Cookie header.** I have no idea why I was getting no cookie with a standard AJAX request in the image from Chrome's connection inspection above. [I'll have to consult the JQuery documentation to see how to fix this.](http://api.jquery.com/jquery.ajax/)

I want to thank you @pmtischler for helping me.

Once I resolve this problem on my end, I'll post my fix on here for anyone else attempting a web-based viewer.
