### ISSUE TITLE
Waypoint Evaluation Enhancement Request

### ISSUE THREAD

**Issue by oneTimePad** [auvsi-suas/interop#253]
Currently, the waypoint section of the mission evaluation export is formatted like this:

![mission waypoint evaluation format](https://cloud.githubusercontent.com/assets/11430814/25730949/909135c0-310f-11e7-858d-d0393f87e55c.png)

3 pieces of information are provided for each evaluated waypoint: scoreRatio, id, and closestForMissionFt. Could you add the id of the closest UAS Telemetry object as a 4th piece of information? That would be great, because then we'd be able to determine which Telemetry object resulted in the closestForMissionFt value without having to manually sift through thousands of Telemetry objects.

Thanks!

**Comment by pmtischler** [comment]
Note that we're returning interpolated data (linear if within telem/velocity bounds), so there isn't an ID necessarily.

Why do you want this information?

**Comment by oneTimePad** [comment]
It would be great to have that information so that we could compare it with our Mission Planner logs and sanity check ourselves.

I didn't realize that you were returning interpolated data - thanks for clarifying that. I assume that all of the interpolated air positions are situated between two UAS Telemetries, correct? Would it be possible to provide the IDs of those two UAS Telemetries?

Thanks

**Comment by pmtischler** [comment]
I agree with you that such data may be useful for analysis / verification. Unfortunately we don't have the resources at this time to support that level of feature scope. You can use the model APIs to create analysis scripts, like [create_teams](https://github.com/auvsi-suas/interop/blob/master/server/tools/team_creator/create_teams.py). You can also use the KML output to analyze in tools like Google Earth.
