### ISSUE TITLE
Not able to forward telemetry

### ISSUE THREAD

**Issue by HobbySingh** [auvsi-suas/interop#256]
Hi,

I have tried forwarding telemetry from mavproxy to server, but I am always receiving error "proxy_mavlink: CRITICAL : Did not recieve mavlink packets for 10 seconds.".

Thats how I am running mavproxy and forwarding telemetry respectively: 
"mavproxy.exe --out=127.0.0.1:14550 --out=127.0.0.1:14551"
"./interop_cli.py --url http://192.168.32.61:8000 --username testuser mavlink --device 127.0.0.1:14550"

I am able to visualize mavlink being recieved in mission planner.
But I have no idea why proxy_mavlink is not able to receive packets.

I have looked inside proxy_mavlink that it is expecting "GLOBAL POSITION INT" but no idea why mavlink msg doesn't contain this.

I am able to read missions from server, upload data but not able to forward telemetry. Please help I have tried it on different platforms : Windows, Linux, OSX , same problem. 
Any help would be appreciated.

**Comment by pmtischler** [comment]
Are you running the `interop_cli` from within the container? If so have you opened the ports on the container to allow such network traffic? See [this doc](https://docs.docker.com/engine/userguide/networking/). If that's the problem, maybe I'll update [run.sh](https://github.com/auvsi-suas/interop/blob/master/client/run.sh) to include `--net=host`.

If not, please describe your setup in more detail.

**Comment by HobbySingh** [comment]
Thanks a lot
