### ISSUE TITLE
Docker Toolbox

### ISSUE THREAD

**Issue by nlocke** [auvsi-suas/interop#258]
Is anybody else using docker toolbox?
If so, does this syntax make sense for it:

FROM python:3

ADD interop_cli.py /

RUN pip install interop

CMD ["python","./interop_cli.py"]

**Comment by nlocke** [comment]
I moved on to try and run the docker file provided in the interop-master/client folder.
Docker runs the file, but then I get a "Client.Timeout exceeded while awaiting headers".
If I have nothing else connected to the machine is this ok or is something wrong?

**Comment by pmtischler** [comment]
This isn't a forum, and the judges don't help debug the custom integrations. Please follow the [docs](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html) for how to use the code in the recommended way.
