### ISSUE TITLE
Python Installation

### ISSUE THREAD

**Issue by JohnPatrickHarris** [auvsi-suas/interop#26]
Attempting to install Python onto our based system as one of the prerequisites. We are unable to pass the initial test. How should we go about installing Python 2 and Python 3 to pass this test?

**Comment by prattmic** [comment]
What do you mean by your "based system"? If you are running the complete environment in a VM, then the setup script should install everything you need.

If you are trying to run the client on your own machines, the installation method for Python varies. Assuming you are using Ubuntu `sudo apt-get install python python3` will install Python 2 and 3, though both are almost certainly already installed. Also note that for the client, you don't *need* Python 2 and 3. We support both, so you can use whichever is more convenient.

**Comment by JohnPatrickHarris** [comment]
We are using Ubuntu and we are attempting to just to pass the system test. And we are unable to pass both Python 2 and Python 3? And sudo apt- get install python python3 gives us that they are both installed and both the newest version.

Will be okay though we have not passed the test.

**Comment by prattmic** [comment]
Can you post the output of the test script? It should work if the setup
script completed successfully.

**Comment by jburgin** [comment]
We have the same issue, both are installed on the system but the test fails:

sudo apt-get install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version.
The following packages were automatically installed and are no longer required:
  libpython-dev libpython2.7-dev python2.7-dev
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
jeff@gummyworm:~$ cd Documents/
jeff@gummyworm:~/Documents$ cd interop/
jeff@gummyworm:~/Documents/interop$ ls
client           data  LICENSE    server  test.sh  tools
CONTRIBUTING.md  docs  README.md  setup   tmp
jeff@gummyworm:~/Documents/interop$ ./test.sh 
Testing server...
Creating test database for alias 'default'...
......................................................................................UAS Post Rate (182.072944)
..........................Obstacle Info Rate (108.362756)
.........................Server Info Rate (135.780597)
...................................................................................................
----------------------------------------------------------------------
Ran 236 tests in 124.598s

OK
Destroying test database for alias 'default'...

=====================================================================

Testing Python 2 client...
./test.sh: line 21: nosetests: command not found

=====================================================================

Testing Python 3 client...
./test.sh: line 29: venv3/bin/activate: No such file or directory
./test.sh: line 30: nosetests: command not found
./test.sh: line 32: deactivate: command not found

=====================================================================

Testing JavaScript Frontend...
21 01 2016 22:10:14.410:INFO [karma]: Karma v0.13.19 server started at http://localhost:9876/
21 01 2016 22:10:14.468:INFO [launcher]: Starting browser PhantomJS
21 01 2016 22:10:17.720:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket /#lnLtf0OCIcm5UxwXAAAA with id 94736440
PhantomJS 1.9.8 (Linux 0.0.0): Executed 15 of 15 SUCCESS (0.049 secs / 0.116 secs)

=====================================================================

Server PASSED
Python 2 client FAILED
Python 3 client FAILED
JavaScript Frontend PASSED

**Comment by prattmic** [comment]
It looks like the setup did not complete successfully. Try running the
setup script again and make sure it reports that it is successful at the
end.

**Comment by jburgin** [comment]
I ran the setup again and there was no change.

**Comment by prattmic** [comment]
Can you post the output of the setup? I recommend using a site like
http://paste.ubuntu.com, since the output is quite long.

**Comment by jburgin** [comment]
I don't have the computer with me right now, but when I get home tonight I will post the output.

**Comment by jburgin** [comment]
http://paste.ubuntu.com/14603609/

**Comment by prattmic** [comment]
Thanks. Digging into the problem, it turns out that the latest release of virtualenv creates a `virtualenv-3.5` binary, even though it should create `virtualenv-3.4` (see pypa/virtualenv#851).

#27 will avoid the bad package and should fix your problem once merged.

**Comment by prattmic** [comment]
I just merged #27 (@pmtischler is very fast today!).

Please pull the latest changes and run setup again.

Before running the setup again, please run `sudo pip3 uninstall virtualenv` on the machine. Since you probably already have the latest version of virtualenv installed (and just need to reinstall it from a different package), pip may decide not to install virtualenv again if you don't uninstall first.

Feel free to reopen the issue if you continue to have problems.

**Comment by KDharmindar** [comment]
In my case I was having the issue because I am using anaconda distribution and it creates virtual environments in anaconda3/envs/ path.
And I was setting some other location.
