### ISSUE TITLE
ODLC image submission issue

### ISSUE THREAD

**Issue by DarkmatterVale** [auvsi-suas/interop#285]
I'm having trouble viewing a submitted ODLC object's image. I have submitted both PNG and JPG files using the client library's ```post_odlc_image``` method, and the upload appears successful (see logs below), but when I attempt to view the image I get the below error:

![2017-09-14 16 53 40](https://user-images.githubusercontent.com/6094957/30455697-de461ef8-996e-11e7-9a3b-d1e36caf33b7.jpg)

Is there something that I am doing wrong?

Here are the logs:
```
requests.packages.urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 10.10.130.2
requests.packages.urllib3.connectionpool: DEBUG: http://10.10.130.2:8000 "POST /api/login HTTP/1.1" 200 17
requests.packages.urllib3.connectionpool: DEBUG: http://10.10.130.2:8000 "POST /api/odlcs HTTP/1.1" 201 None
requests.packages.urllib3.connectionpool: DEBUG: http://10.10.130.2:8000 "PUT /api/odlcs/13/image HTTP/1.1" 200 15
```

I am using the newest version of the interoperability server and the newest version of the interoperability client library.

Thanks for the help!

**Comment by pmtischler** [comment]
`/media` is not a path we've said to use. That is an internal path within Django for media files, a path which is typically disabled in production Django servers for security reasons.

`get_odlc_image` is the client API for retrieving an image previously uploaded.

Use the [review object imagery](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html#performance-evaluation) admin page to see what judges would see, and use the automatic evaluation tools to grade it.
