### ISSUE TITLE
ImportError: cannot import name Odlc

### ISSUE THREAD

**Issue by akashcas** [auvsi-suas/interop#289]
```Traceback (most recent call last):
  File "./tools/interop_cli.py", line 14, in <module>
    from interop import Odlc
ImportError: cannot import name Odlc```

**Comment by pmtischler** [comment]
You need to provide more details than that to debug it. It provides almost nothing to investigate or change.

Our CI indicates the last master build was a [success](https://travis-ci.org/auvsi-suas/interop/builds/267553281) and we have a [smoke test](https://github.com/auvsi-suas/interop/blob/master/client/tools/interop_cli_test.py) which would catch this error if it was real.

You've most likely run the program in a non-recommended way. Please follow the instructions [here](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html).
