### ISSUE TITLE
where is "requests"

### ISSUE THREAD

**Issue by Onursevig** [auvsi-suas/interop#291]
I tried to use client library but when I start it , an error says that requests module not found
ModuleNotFoundError: No module named 'requests'

**Comment by pmtischler** [comment]
`requests` is a Python module installed as a system dependency via `apt` or `pip`. It's installed automatically into the Docker package for you. You must not be following the [Getting Started](http://auvsi-suas-competition-interoperability-system.readthedocs.io/en/latest/getting_started.html) instructions.
