### ISSUE TITLE
odlcs image post error

### ISSUE THREAD

**Issue by Onursevig** [auvsi-suas/interop#292]
we try to post and odlcs image by your guide in internet ,we treid every other commend on the interface specification page and they worked but post image is not working.error type is 400 and it says that image is not posting properly way but we try to send a image that we get by GET function from server which is a image in the interop file .we try to transfer that image to binary content and post but get error 400

**Comment by pmtischler** [comment]
I didn't follow most of that. 

Error code 400 means you're sending an invalid request, that you're using it wrong. You don't provide any details to how you're doing it, so I can't provide any advice. You do mention using GET, which isn't the method listed on the spec page for uploads.
