### ISSUE TITLE
Add ADLC fields to target submission

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#30]
The interoperability target submission interface needs whether the team is eligible for ADLC credit or not. We need 3 boolean fields as to whether a given target was automatically detected, classified, and/or localized.

* Update the code
* Update the interface
* Update the docs
* Notify teams via Google Groups

**Comment by pmtischler** [comment]
Any update on this?

**Comment by prattmic** [comment]
A single boolean 'autonomous' field will suffice. Per section 7.3, they get localization credit if the position is within 150ft, and characterization credit if three characteristics are correct. The first six detected targets must be submitted.

**Comment by pmtischler** [comment]
SG
