### ISSUE TITLE
Add submission time for targets, use for Actionable Intelligence

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#31]
Targets which are submitted during the first flight period should get actionable intelligence credit. If teams update the target after the first flight period, they won't get credit for actionable intelligence. To handle this we need to add a timestamp for the submission.

* Update code
* Update interop interface & docs
* Notify teams

**Comment by pmtischler** [comment]
We should have a timestamp for first created, and for last updated.

**Comment by pmtischler** [comment]
See #55 for how we will judge actionable intelligence.

**Comment by pmtischler** [comment]
I believe this is complete? You added the create/modified times.

**Comment by prattmic** [comment]
The code is done, I should update the docs.

**Comment by pmtischler** [comment]
Actually, do you want to create a PR to auto-grade actionable, or should I?

**Comment by prattmic** [comment]
I can do this.

**Comment by pmtischler** [comment]
With #118, I believe this is done.
