### ISSUE TITLE
Division by zero at runtime in stationary obstacle collision detection

### ISSUE THREAD

**Issue by GodCed** [auvsi-suas/interop#312]
Running our mission simulations we encounter false detections of stationary obstacles collisions.
Looking at the `interop_server_error.log` we find this warning at time of mission evaluation.

`[Sun Jun 10 03:11:40.627032 2018] [wsgi:error] [pid 93:tid 140605378291456] 2018-06-10 03:11:40,626 WARNING stationary_obstacle /interop/server/auvsi_suas/models/stationary_obstacle.py:92: RuntimeWarning: divide by zero encountered in cdouble_scalars`

`[Sun Jun 10 03:11:40.627058 2018] [wsgi:error] [pid 93:tid 140605378291456]   zcalc = ((root - y1) * (z2 - z1) / (y2 - y1)) + z1`

We looked trough our uas telemetry (coming from our UAV simulator) and found consecutive points where `start_lat` and `end_lat` are exactly the same. We think this leads to `y2-y1=0`, causing the runtime exception and the function to return True.

Does this make any sense or are we really colliding with the obstacles in another way?

**Comment by pmtischler** [comment]
This is definitely a bug in the code, thanks for finding it!

I've written #313 which is a quick but not necessarily clean fix. I've filed #314 for after competition to clean this up.
