### ISSUE TITLE
Add version tags for the interop server Docker images

### ISSUE THREAD

**Issue by bbridges** [auvsi-suas/interop#339]
Since it's been stated that some breaking changes are expected to be introduced for the 2019 competition, and can be seen in issues like #325, it would help to tag different versions of the interop server before pushing them to Docker Hub (such as build dates, semver-like versions, etc.). Currently only a `latest` tag is available.

This would help a lot in cleaning up noise in CI pipelines, where the version of the interop server can be pinned for a particular build. Unrelated changes won't have build failures pop up in the case that the `latest` tag gets pushed to again.

**Comment by pmtischler** [comment]
#340 will automatically add the date (month granularity) as a tag as part of deploy during merge into master.

We won't make any guarantees on how long we'll keep tags around. As of now, there appears to be no limit to number of tags on the hub, but I've seen that at around 100 it becomes problematic for tooling.

**Comment by pmtischler** [comment]
Version 2018.09 is available and should be stable/non-moving/non-updated as of tomorrow (October).
https://hub.docker.com/r/auvsisuas/interop-server/tags/

**Comment by bbridges** [comment]
Great, thanks!
