### ISSUE TITLE
Add SUAS judge frontend to replace Django Admin interface

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#37]

**Comment by OttoJursch** [comment]
What sorts of features are going to be added with this? Will we be able to create missions via a map interface?

**Comment by pmtischler** [comment]
It's unlikely that we will include a map interface. Such takes a ton of time and requires data we likely don't have access to. If we were to add anything like it, it'd be a way to import something exported from an existing mapping application. I wouldn't count on such.

This is more for a compressed web form (rather than 3 levels of indirection just to note the home position), and for a REST interface (although there already exists an admin programmatic interface). This is the lowest priority issue we have, and our timing estimate is "sometime before competition", assuming we get to it.

**Comment by pmtischler** [comment]
Although it'd be nice to have, I don't think it's even close to mission-critical and represents only a small benefit. Given the large list of higher priority items (not all are filed as issues), I'm going to close this.

@yogishadixit @prattmic If you have the free time to handle this, feel free to reopen and assign.
