### ISSUE TITLE
docker interop image fails building

### ISSUE THREAD

**Issue by cappellino** [auvsi-suas/interop#381]
Hi, I'm trying to build the client docker image.
I installed with pip what there is in requirements.txt, and I installed docker.
Then i tried to run:
`docker build -t interop_client_test . `
and it works until step 5/10. 
Then it gives me this error:

> `Processing triggers for ca-certificates (20180409) ...
> Updating certificates in /etc/ssl/certs...
> 0 added, 0 removed; done.
> Running hooks in /etc/ca-certificates/update.d...
> done.
> Removing intermediate container 99dcae778bf1
>  ---> ebc7245f5ad3
> Step 5/10 : COPY client/requirements.txt .
> COPY failed: stat /var/lib/docker/tmp/docker-builder007404179/client/requirements.txt: no such file or directory

I got this error also with a clean installation of Ubuntu. 
I don't know if it's a problem of the code or I'm missing something. Thank you

**Comment by pmtischler** [comment]
Teams are not required to build the image. Please read the Getting Started guide on the wiki.

**Comment by rtumac** [comment]
@cappellino use the https://github.com/auvsi-suas/interop/blob/master/client/build.sh script to build the image
