### ISSUE TITLE
executing code inside docker

### ISSUE THREAD

**Issue by cappellino** [auvsi-suas/interop#383]
Hi, sorry for the maybe stupid question, but how do I run my python code (with all the library needed) inside docker? should I install all I need with pip inside docker and then import my code and run it inside docker? Or docker it's used only to send/receive from/to server? And in this case how do I execute docker inside my code? Thank you

**Comment by pmtischler** [comment]
The judges don't help the teams figure this out beyond the provided documentation, which includes links to learning Docker. From your question, I don't think you understand what Docker is or why we use it in this repo. I recommend first learning what Docker is and how to use it, then you may answer your own question.

https://www.docker.com/why-docker
https://docs.docker.com/get-started/

To be more direct, you can extend the client container, manually add things into it, or not use the client container at all. You could use the repo code directly with our provided Pip integration. You don't need to use the client library either, and can make http+json requests directly.
