### ISSUE TITLE
Docs build failing, causing Travis tests to fail

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#41]
Example:
https://travis-ci.org/auvsi-suas/interop/builds/105410327

**Comment by prattmic** [comment]
Wow, this took way too long to track down. It turns out that there is a bug in Sphinx and/or Pygments. Sphinx reuses a stateful Pygments object between `sourcecode` blocks, so one block can affect the parsing of another. I'm going to file a bug on them, and put up a work-around PR shortly.
