### ISSUE TITLE
Bug: No field "active" using get_mission(1)

### ISSUE THREAD

**Issue by xShudow** [auvsi-suas/interop#413]
I'm getting an issue using the new interop server update. I have updated the api and interop server. When using the get_mission(1), I get the following error:
![image](https://user-images.githubusercontent.com/44326630/58049362-82229900-7b01-11e9-910d-3f1825323064.png)
I used the following lines to attempt to get mission details.
![image](https://user-images.githubusercontent.com/44326630/58049413-a7170c00-7b01-11e9-89c6-fe467b4ead54.png)

Looking at the new API update to the interop_api_pb2.py file, I see the addition of the new auvsi_suas.proto.Mission.stationary_obstacles descriptor field due to the new update to interop; however I do not see the "active" descriptor field that the error is describing is missing. I followed the commands list in https://github.com/auvsi-suas/interop/blob/master/client/Dockerfile to ensure that the interop client library and interop_api_pb2.py file has been updated. 
How can this be fixed? I have followed the Getting Started Guide; does it need to be updated to reflect new changes?

**Comment by pmtischler** [comment]
You need to update your containers:
https://github.com/auvsi-suas/interop/wiki/Getting-Started#update-container-image
