### ISSUE TITLE
Bug: Telemetry() upload failed.

### ISSUE THREAD

**Issue by xShudow** [auvsi-suas/interop#414]
I have followed the Getting Started Guide and updated the interop server and api changes to the interop client library. 

When executing the following lines, I get the following error:
![image](https://user-images.githubusercontent.com/44326630/58052008-9027e800-7b08-11e9-826d-99ebfc8aab16.png)
![image](https://user-images.githubusercontent.com/44326630/58052046-a59d1200-7b08-11e9-9d02-28691887f0c8.png)
![image](https://user-images.githubusercontent.com/44326630/58052072-b8174b80-7b08-11e9-9537-059a6006456e.png)

Looking at the interop_api_pb2.py file, the descriptor fields allowed are latitude, longitude, altitude, and heading; however, according the error provided when communicating with the new interop server, it wants latitude, longitude, altitude_msl, and uas_heading.
![image](https://user-images.githubusercontent.com/44326630/58052196-0593b880-7b09-11e9-82ec-1547a5c94d00.png)

How can I fix this? Does the Getting Started Guide need to be updated to reflect the interop server changes?

**Comment by pmtischler** [comment]
You need to update your containers:
https://github.com/auvsi-suas/interop/wiki/Getting-Started#update-container-image
