### ISSUE TITLE
Moving Wiki to README

### ISSUE THREAD

**Issue by Justin2997** [auvsi-suas/interop#416]
I propose moving the wiki documentation to a README file with structure. Maybe something like /doc file. This will add visibility to the documentation and assure history of the documentation because wiki can be modified without a commit. 

I propose to make the PR to add the doc in the code is that something the community approved.

Thanks for the great work.

**Comment by pmtischler** [comment]
The documentation is linked to from the home page README.

As far as I know README files force everything onto a single page, which would be less convenient than the current multi-page structure. The wiki does have history- it's versioned in it's own Git repo. 

Is there something I'm missing?

**Comment by pmtischler** [comment]
I've done this anyway- certainly makes my life easier though removes some page-level structure for teams.

**Comment by Justin2997** [comment]
You can do a Table of Contents in your README. But I like that README now. Thanks.
