### ISSUE TITLE
Add target types to interoperability client

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#44]

**Comment by pmtischler** [comment]
@prattmic 

I started to work on this issue, and I'm wondering what's the best way to handle the enumeration of acceptable types. In my branch I've imported the enums from the server, and I've updated the requirements to reference the server's (though it's not correct atm). This doesn't seem like the best way to do it. Thoughts?
* [types.py](https://github.com/auvsi-suas/interop/blob/target-types/client/interop/types.py)
* [requirements.txt](https://github.com/auvsi-suas/interop/blob/target-types/client/requirements.txt)

**Comment by prattmic** [comment]
No, we shouldn't depend on the server in the client. I think the simplest
solution is to just copy the enums and have duplicates in the server and
client. I would also be OK with moving them to the client and making the
server depend on the client.

**Comment by pmtischler** [comment]
I agree client shouldn't depend on server. I don't think server should depend on client. Duplicating it seems uni-deal from maintenance standpoint.

The client doesn't have full correctness checking for other interfaces- it simply does sanity checks. I think trying to duplicate validation logic on both sides is not worth our time. I think we should just remove the non sanity-checks and let the server respond with an error to notify students of the mistake. Agree?

**Comment by prattmic** [comment]
Regardless of checks, I think it is nice to provide an enum of values for teams to use, but I don't think it is critical or urgent.

**Comment by pmtischler** [comment]
Need to add upload of target image.
