### ISSUE TITLE
Add objects to capture mission clock.

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#45]
Enables the interoperability system to judge total mission time.

Enables the future target review system to know when targets can be considered frozen and ready for review.

@prattmic Thoughts before I start?

**Comment by prattmic** [comment]
Nothing in particular. Big buttons for each event (mission start, time out, etc) seems reasonable. Making previous times editable on the same page would be nice too, but lower priority. We could go into the admin interface to edit times.

**Comment by pmtischler** [comment]
Ok. I was thinking the same workflow as TakeoffOrLandingEvents for now, and then make an interface for this in #37.

**Comment by pmtischler** [comment]
Upcoming PRs:
1) Refactor TakeoffOrLandingEvent.flights so generic implementation it is part of TimePeriod.
2) Refactor TakeoffOrLandingEvent.user_in_air so it uses a function in AccessLog which gets the latest access log before a time. 
3) Add a method similar to flights and user_in_air to MissionClockEvent in order to get the on-mission-clock periods, on timeout periods, and whether the user is on mission clock / timeout.
4) Add grading of time-on-mission-clock.
