### ISSUE TITLE
Odlc review 

### ISSUE THREAD

**Issue by nxvaa** [auvsi-suas/interop#466]
hi I’m kinda new to this so I’m sorry for any inconvenience, After I ran the interop server on windows I ran the client on Ubuntu VBox everything is fine but I can’t really find the odlc directory on the server to view the file I sent. I get this message “upload_odlcs: INFO: Found odlc-image pairs: {}” so how can I review the image? Sorry If I’m not clear and thanks in advance!

**Comment by pmtischler** [comment]
`upload_odlcs: INFO: Found odlc-image pairs: {}`
This indicates that the interop CLI found no json+image file pairs for which to upload, so no ODLCs were uploaded. You can see [here](https://github.com/auvsi-suas/interop/blob/421d42bb967a931d6d0cc31e345b06e8cdee8eba/client/tools/upload_odlcs.py#L70-73) that the code next loops over an empty map so it never calls any upload code.

Once you've uploaded ODLC data, follow the steps in the [Getting Started guide](https://github.com/auvsi-suas/interop/blob/master/README.md#performance-evaluation) for reviewing the ODLC data and computing a score.
