### ISSUE TITLE
How to determine the correct Mission ID?

### ISSUE THREAD

**Issue by bjubes** [auvsi-suas/interop#468]
After logging in, how does a team determine the correct mission ID to use? In order to get a mission, we must have an id to get mission data from /api/missions/:id. I had assumed that this was the same id given to our team under the /api/teams endpoint. 

However, in the test configuration, testuser has a team id of 2, but the only valid mission id is 1. 

Are these ID's not the same? if not, how do we know what mission ID is ours after logging in?

**Comment by mathisgag** [comment]
The mission Id is given by the judges along with the username, password, and connection to the server (Ethernet cable). The team Id is separate and is not related to the mission Id.

**Comment by pmtischler** [comment]
At competition, connection details and credentials are given at check-in, mission id and Ethernet are given at setup time.

We purposely don't provide a list API or the id until setup to avoid programming mistakes. If you don't specify they id we give you, you're unlikely to download the wrong mission id by mistake.

The mission id in the teams API won't be populated until you've taken off. That field isn't intended for use by students in a meaningful way. The judges use the same API to monitor.
