### ISSUE TITLE
New Mapping Task

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#483]
* Mission details
  + Map center GPS position.
  + Map height in feet.
* CRUD an image map for the mission.
  + 16:9 aspect ratio.
  + PNG or JPG format.
  + Up to 1MB in size.
* Interop CLI for image map.
* Judge specified quality field added to scoring:
  + `HIGH` at 100% points.
  + `MEDIUM` at 50% points.
  + `INSUFFICIENT` at 0% points.
* Mapping scored at 10% of points, avoidance dropped from 20% to 10%.
* Frontend for setting the quality score.
  + May be best to wait for Angular transition and rely on Django admin in interim.

**Comment by coderkalyan** [comment]
What's the mapping task about, may I ask? Or do I need to wait for the official rules to be released? :smiley:
