### ISSUE TITLE
Previous Data 

### ISSUE THREAD

**Issue by montathar111** [auvsi-suas/interop#513]
I am searching for the data from 2019 and before but I did not find it. 
i want to see how the waypoints will be represented in the competetion.
So please where can I find it ?

**Comment by pmtischler** [comment]
This is covered in the Getting Started section of the README:
https://github.com/auvsi-suas/interop#first-time-setup

This will run the `load_test_data` command:
https://github.com/auvsi-suas/interop/blob/master/server/interop-server.sh#L35

Which will internally run the `create_sample_mission()`:
https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/models/test_utils.py#L36
