### ISSUE TITLE
Interop API Map Submission Verification

### ISSUE THREAD

**Issue by KrishnanS2006** [auvsi-suas/interop#518]
Hello,

Is there currently any way to view and verify team map submissions through the Interop Admin Dashboard, similar to viewing ODLC Images? I would like to check whether some code for uploading our map image works, and I was hoping there would be some way to view the submitted map image through the Admin Dashboard on the Interop Server. However, I can't find any page that even confirms the fact that a map has been submitted to the Interop server. Is this still to be implemented, or is there some way to verify our submission for now?

Thanks for your help!

**Comment by pmtischler** [comment]
Please see this point in the guide:
https://github.com/auvsi-suas/interop#review-map-imagery

You can track development of the feature at #496.
