### ISSUE TITLE
Executing commands on the virtual environment?

### ISSUE THREAD

**Issue by lolcocks123** [auvsi-suas/interop#533]
Hello,

I am kind of a newbie when it comes to virtual environments. I have been assigned this task but I am kinda stuck and don't know how to move past this issue

After I run `sudo ./interop-client.sh run` I am sent to a virtual environment. After which, I can run `./tools/interop_cli.py --url http://10.10.130.2:8000 --username testuser mission --mission_id 1` to get the mission.

Now the problem I ran into is that, I do not know how to automate it.

Like how can I execute the second command to a virtual environment and save its output (the mission) to a text file so that it can be sent for further processing.

I apologize if this is kind of a newbie question but I am stuck with no idea what to do.
I tried using Python to execute commands on the virtual environment but I don't think I was on the right track and those commands probably got executed straight up on standard terminal.

Can someone please help me? Thank you.

**Comment by pmtischler** [comment]
The "virtual environments" you refer to are [Docker](https://www.docker.com/) containers. Please go through the [prerequisite knowledge](https://github.com/auvsi-suas/interop#prerequisites) section of the README which provides links to all the technologies used.

Keep in mind you don't need to use the Docker container, and you don't need to use any competition provided code. The interop server provides a standard HTTP-JSON interface you can use directly with most programming languages. 

If you wanted to use the interop containers, you can use [Volumes](https://docs.docker.com/storage/volumes/) to get files out of the container. You can pair this with a specific `run` command similar to how the `interop-client` bash script does for [running tests](https://github.com/auvsi-suas/interop/blob/master/client/interop-client.sh#L39). Alternatively, you could build a new image with the interop image as a base layer, enabling you to add your own custom code and automation on top of the interop contents.

You'll need to take it from here though.
