### ISSUE TITLE
Error while using post_odlc

### ISSUE THREAD

**Issue by a1234jehad** [auvsi-suas/interop#537]
Although I can post_telemetry data... when i try to post an ODLC object its says the following error:

`auvsi_suas.client.exceptions.InteropError: POST http://127.0.0.1:8000/api/odlcs -> 4
00 Error (Bad Request): ODLC mission is required.`

**Comment by pmtischler** [comment]
That's because you didn't include the ODLC mission ID in the request, per the error message.

HTTP code 400 means your request was bad.
"ODLC mission is required" is why your request was bad.

**Comment by a1234jehad** [comment]
Can you explain more? where can I put the ODLC mission ID? the post_odlc() function takes only an Odlc object..

**Comment by pmtischler** [comment]
Please read the API documentation that you're trying to use:
https://github.com/auvsi-suas/interop/blob/master/README.md#object-detection-localization-classification-odlc
https://github.com/auvsi-suas/interop/blob/master/proto/interop_api.proto#L165
