### ISSUE TITLE
Error 500 when accessing admin page

### ISSUE THREAD

**Issue by revahsta** [auvsi-suas/interop#66]
When accessing the admin page, a 500 error is received.

Error log:
[interop_server_error.log.txt](https://github.com/auvsi-suas/interop/files/148736/interop_server_error.log.txt)

**Comment by prattmic** [comment]
Looks like an issue with https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/views/middleware.py

`process_response` is called without calling `process_request`?

**Comment by pmtischler** [comment]
Fixed in #67
