### ISSUE TITLE
 Test target workflow error

### ISSUE THREAD

**Issue by justineaster** [auvsi-suas/interop#69]
For both python2 and python3 we are failing the  Test target workflow test.

link to output: http://pastebin.com/STZxT2Dt

**Comment by prattmic** [comment]
If you just updated to the latest software, you need to run the
provisioning again to ensure the database is up to date and server is
restarted.

**Comment by justineaster** [comment]
setup.sh was run before running test.sh

**Comment by prattmic** [comment]
Try manually restarting Apache ('sudo service apache2'). If that doesn't
work, please post the server logs.

**Comment by prattmic** [comment]
sudo service apache2 restart

**Comment by justineaster** [comment]
Restarting the server fixed the issue. Thanks!
