### ISSUE TITLE
Username and Pasword

### ISSUE THREAD

**Issue by sharma16aug** [auvsi-suas/interop#7]
While running the file i'm having this particular issue i.e. username and password invalid. I'm using the default values as username and password i.e. username,password and also tried testadmin and testpass.
Altthough i am able to run the judges server but can't run the client server. both the clients failed.
please help ASAP

**Comment by prattmic** [comment]
How did you perform setup?  If you used the automatic provisioning, via ``vagrant up``/``setup.sh``, the admin username and password will be ``testadmin``/``testpass``. There is also an unprivileged user, ``testuser``/``testpass``. The client tests use those users, do they pass?

You can also manually create an admin user:

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py createsuperuser
```

**Comment by sharma16aug** [comment]
i have created a dedicated machine using linux and used setup.sh to setup the server.

**Comment by prattmic** [comment]
That should have created an admin user. Regardless, you can create your own admin user with the above command, or to install the ``testadmin`` user with ``manage.py``:

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py loaddata fixtures/test_admin.yaml
```

To install all of the test data required for the client tests:

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py loaddata fixtures/test_fixture.yaml
```

**Comment by DarkmatterVale** [comment]
I believe I am getting the same error. I have put the full stack trace on Pastebin. I am not sure how to fix this. What do you suggest?

http://pastebin.com/PqiPaZfx

**Comment by sharma16aug** [comment]
as told by @DarkmatterVale the same error is stil recieved by me.

**Comment by prattmic** [comment]
@sharma16aug Are you are still receiving the same error after trying the ``loaddata`` command I suggested?

@sharma16aug and/or @DarkmatterVale could you provide a dump of the database you have? Run:

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py dumpdata --format yaml -o db.yaml
```

And upload ``db.yaml``. This will let us verify whether the user is in the database at all.

Do either of you happen to still have the output of ``setup.sh`` that you can upload (even just the end). Unfortunately, we don't currently log it to a file, so it will only be around if you still have that terminal, but it should not have completed successfully without installing this user.

**Comment by DarkmatterVale** [comment]
@prattmic Sorry, but I did not save the output of ```setup.sh```. It did appear to run correctly however, because it did not stop and quit at any point in time.

I am not able to run the above commands. I get this error:

```
CommandError: Unable to serialize database: No module named yaml
```

It might be due to ```puppet``` maybe not being run properly? Is there something I need to run other than ```setup.sh```?

**Comment by prattmic** [comment]
Try changing --format to json.  We may not install YAML by default.

**Comment by DarkmatterVale** [comment]
Here is the link to the pastebin:

http://pastebin.com/cmQqicsz

**Comment by prattmic** [comment]
It looks like none of the default data was loaded into your database.

Try loading the test fixture: (this is what should have been installed)

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py loaddata fixtures/test_fixture.yaml
```

It should print some number of fixtures installed.

No worries about not keeping ``setup.sh`` logs. I don't expect folks to think to log it, but I figured I'd ask. I'm going to submit a change soon to start logging output by default for each run so we will have it.

**Comment by DarkmatterVale** [comment]
Here is the output from running those commands:

```
Installed 0 object(s) from 0 fixture(s)
```

Is this my problem? Do I need to install a set of fixtures?

**Comment by pmtischler** [comment]
Yes. The fixture is the file `fixtures/test_fixture.yaml`, and it should have objects in it, one of which is the test user.

**Comment by prattmic** [comment]
Hm, you couldn't export YAML before, perhaps this is the same problem, but
loaddata is being quiet about it.  Try installing PyYAML, I think it is
missing from our list of dependencies.

```
$ cd ~/interop/server
$ source venv/bin/activate
$ pip install PyYAML
```

Then try the loaddata command again.

**Comment by DarkmatterVale** [comment]
That loaded the data properly. The output was ```Installed 18 object(s) from 1 fixture(s)```

I am testing the clients once more, hopefully it will work :)

**Comment by prattmic** [comment]
We now install PyYAML in automated setup.

@sharma16aug this should fix your problem as well. Just ``git pull`` the latest version of the repo, and run ``setup.sh`` again (or install PyYAML like @DarkmatterVale did).

**Comment by sharma16aug** [comment]
@prattmic I'm still getting the same error even after creating the data base. the test.sh script fails.

here's the link to the output. http://pastebin.com/hgXMnP4j

**Comment by prattmic** [comment]
Hm, it looks like the data was installed correctly.

I don't think it should be necessary for the server to pick up the changes, but can you try restarting Apache and rerunning the tests?

```
$ sudo service apache2 restart
```

If that doesn't work, can you upload a database dump like @DarkmatterVale did?

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py dumpdata --format json -o db.json
```

**Comment by sharma16aug** [comment]
here's the link to the db.json file :-  http://pastebin.com/QbiuvV8v
also i'm getting this dependency error whenever i'm running setup.sh :- http://pastebin.com/EbMDv6hP
still getting the error even after making a clean install of the server once again.

**Comment by pmtischler** [comment]
The error says it's timing out when executing the Karma and Jasmine installation. The installation is done via [NPM install command](https://github.com/auvsi-suas/interop/blob/master/setup/puppet_files/auvsi_suas/manifests/server_install.pp#L38). The default is 300s, so I'm rather confused why it isn't succeeding.

**Comment by sharma16aug** [comment]
basically the problem is during installation and not with the server script. If on another system it gets installed then the server and client will run smoothly, isn't it ?

**Comment by pmtischler** [comment]
Yes that should be true. I haven't seen this error before, usually it's a non-issue.

**Comment by sharma16aug** [comment]
OK. Thanks a lot. I will try it on another machine,and will surely let you know about any problem if persists again

**Comment by pmtischler** [comment]
Closing for now, please reopen if the error returns and persists.
