### ISSUE TITLE
python client failed

### ISSUE THREAD

**Issue by rishabhjoshi750** [auvsi-suas/interop#74]
I cloned the repositrie of interop from github and after going through all the steps i encounter this error "python client failed"(both of the clients failed). but server and frontend passed.

here is the link to the terminal output i'm getting :- http://pastebin.com/c6v5rP1R
please help

**Comment by prattmic** [comment]
Do you have the output from the setup script? The errors like `/interop/test.sh: line 8: venv/bin/activate: No such file or directory` indicate that the setup did not complete successfully.

**Comment by rishabhjoshi750** [comment]
her's the link to the output
 http://pastebin.com/c6v5rP1R

**Comment by prattmic** [comment]
Yes, I saw that; I mean the `setup.sh` script that must be run before running tests. (http://auvsi-suas-competition-interoperability-system.readthedocs.org/en/latest/setup/machine_or_vm.html#automated-system-setup)

**Comment by rishabhjoshi750** [comment]
http://pastebin.com/SXkt6NRT
this is what i'm getting after running the test.sh script.

**Comment by pmtischler** [comment]
Fwiw, your attempt to force an upgrade didn't specify the package to upgrade.

**Comment by pmtischler** [comment]
@rishabhjoshi750 please `git pull` and try setting up on a clean machine.
