### ISSUE TITLE
Provide a check for duplicate telemetry data

### ISSUE THREAD

**Issue by legonigel** [auvsi-suas/interop#75]
I think it would be helpful for teams to have a way to check that the information which we send to the interop server does not contain duplicate data. It wouldn't necessarily be built in to the server, but could be a script provided in the repo.

I am suggesting this as an enhancement, but it is not something my team is counting on.

**Comment by prattmic** [comment]
You are correct, this is not something we provide right now. During development and testing, you can verify your data with a little work.

A [`GET /api/telemetry`](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/views/telemetry.py#L88) API endpoint is available. It is only available to superusers (i.e., the admin account), so it isn't documented in the primary interop documentation, but you can use it during development and testing to verify the data that has been sent.

We also have a [method](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/models/uas_telemetry.py#L51) that deduplicates telemetry logs. It isn't accessible from outside the server, but with a little extra work, the server could be modified to warn you about duplicate data.

**Comment by pmtischler** [comment]
There are many scripts like this which may be useful for teams. It's one of my personal goals to decrease the effort required by student teams, and to enable them to focus on topics of innovation. Unfortunately this type of thing is not something we presently have time to provide or maintain. In terms of interop, we are currently focused on core system requirements needed at competition and we expect this to take all of our time between now and June. We are also overhauling all other systems used at competition (from SRIC to grading to banquet presentations). If in the future we have more contributors then we can consider supporting such tooling.

I recommend looking at [create_teams.py](https://github.com/auvsi-suas/interop/blob/master/tools/team_creator/create_teams.py) which demonstrates how to write a standalone script that can connect to the database and use the model methods (like the `dedupe` method prattmic@ mentioned). If you set it up correctly, it could be as simple as:

```
flight_periods = TakeoffOrLandingEvent.flights(user)
uas_period_logs = UasTelemetry.by_time_period(user, flight_periods)
uas_logs = list(itertools.chain.from_iterable(uas_period_logs))
deduped_uas_logs = list(itertools.chain.from_iterable(
        [UasTelemetry.dedupe(logs) for logs in uas_period_logs])
# Compare logs
```

**Comment by legonigel** [comment]
Thanks for the reply.

If I have read the code correctly, teams can use the `evaluate_teams` endpoint in `auvsi_admin` to check their telemetry rate. This endpoint is already implemented, so it could be used to check the data rate of desuped telemetry logs, but does not provide the direct telemetry logs.
