### ISSUE TITLE
Finish documentation for MissionPlanner integration

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#83]
[TODO(jemoster)](https://github.com/auvsi-suas/interop/blob/master/docs/integration/mission_planner.rst)

**Comment by pmtischler** [comment]
@prattmic Can you take this?

**Comment by prattmic** [comment]
I've never actually used Mission Planner, so I may not be best for this.

**Comment by pmtischler** [comment]
Neither have I :(
