### ISSUE TITLE
Finish documentation for interop client

### ISSUE THREAD

**Issue by pmtischler** [auvsi-suas/interop#84]
[TODO(prattmic)](https://github.com/auvsi-suas/interop/blob/master/client/README.md)

**Comment by pmtischler** [comment]
We should also update the docs/ for information on the interop client.

**Comment by prattmic** [comment]
I can do this

**Comment by akashcas** [comment]
Can u please confirm us the documentation for mission planner as well interop client documents

**Comment by prattmic** [comment]
@akashcas That is covered by #83 

tl;dr, run `clientproxy.py` with the appropriate arguments as a normal Python program and run `auvsi_mp.py` inside the Mission Planner scripting interface.

https://github.com/auvsi-suas/interop/tree/master/client/missionplanner

**Comment by pmtischler** [comment]
@akashcas The rules are very clear. It is the judge's responsibility to provide a test server which implements the interoperability API as defined by the rules. The rules specify it is the responsibility of the team, not the judges, to integrate with this API. The mission planner integration, and both documentations are not covered by our responsibilities as defined in the rules, so you should place no expectation we will finish such or help you debug such.

That being said, when possible we try to make it easier for teams and to save them time by providing tooling. You may find, however, certain requests and debugging help will be de-prioritized.

**Comment by pmtischler** [comment]
Is this complete?

**Comment by prattmic** [comment]
We'll call it done for now, though it could really use more detail.
