### ISSUE TITLE
clientproxy.py error

### ISSUE THREAD

**Issue by akashcas** [auvsi-suas/interop#85]
getting an error in the file while running with appropriate argument. Syntax error
```
 print 1 / (new_time - self.last_telemetry)
```

**Comment by prattmic** [comment]
I assume you are using Python 3? That script was written for Python 2. We need to update it to support both Python 2 and Python 3. If you don't have Python 2, I believe that it will work on Python 3 if you simply replace all three of the print statements with print functions.

i.e.,

```py
print(1 / (new_time - self.last_telemetry))
```

**Comment by akashcas** [comment]
yeah it worked , but i gave me a new error 
```
line 1, in <module>
    from SimpleXMLRPCServer import SimpleXMLRPCServer
ImportError: No module named 'SimpleXMLRPCServer'
```

i tried installing SimpleXMLRPCServer using pip but can't get success .

**Comment by prattmic** [comment]
Ah, it looks like SimpleXMLRPCServer was renamed in Python 3: https://docs.python.org/2/library/simplexmlrpcserver.html

You can try replacing `from SimpleXMLRPCServer import SimpleXMLRPCServer` with `from xmlrpc.server import SimpleXMLRPCServer`, or you can wait until we have a proper update (or use Python 2).

**Comment by akashcas** [comment]
OK I will try out with python 2 and will wait for update for python 3. Team needs to complete this well before 18 may as per the rule book so hope that it will be updated in well advance so that we can figure out each and everything .

**Comment by akashcas** [comment]
one more error while running 
```
    from interop import AsyncClient
ImportError: No module named interop

```

**Comment by akashcas** [comment]
I successfully ran the file but i am getting timeout.As this file should be running while we need run script in mission planner . Here is the output
```
C:\Users\nishi\Desktop\interop-master\client\missionplanner>python clientproxy.py --url http://192.168.0.4:80 --username testadmin --password testpass
Traceback (most recent call last):
  File "clientproxy.py", line 53, in <module>
    password=cmd_args.password)
  File "clientproxy.py", line 14, in __init__
    password=password)
  File "C:\Python27\lib\site-packages\interop\client.py", line 301, in __init__
    self.client = Client(url, username, password, timeout)
  File "C:\Python27\lib\site-packages\interop\client.py", line 46, in __init__
    'password': password})
  File "C:\Python27\lib\site-packages\interop\client.py", line 73, in post
    r = self.session.post(self.url + uri, timeout=self.timeout, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.0.4', port=80): Read timed out. (read timeout=1)
```

**Comment by prattmic** [comment]
That invocation looks correct. Check that you can access http://192.168.0.4:80 in a web browser on the same machine. If not, there is some networking problem.

**Comment by akashcas** [comment]
I got my mistake . I need to change the Python 3 script back to Python 2 . I didn't do that . It's working fine

**Comment by akashcas** [comment]
I was able to access that through web browser
