### ISSUE TITLE
Clarification on Login Cookie

### ISSUE THREAD

**Issue by Codexer** [auvsi-suas/interop#91]
Hello,

The documentation states that the POST /api/login endpoint returns a session id or cookie (stored as Set-Cookie in the response) that must be resent to verify all future requests. The documentation also suggests preparing for errors that involve logging in again in case of failure. 

However, the login view only returns Django's standard HttpResponse with a message (line 51, login.py). My team has tried resetting the server and changing attributes of the user; the only thing required for a 200 request is a previous login, without storing any cookie. 

Does our client need to worry about a cookie from the POST /api/login endpoint?

Thank you,
- Matt T / RU Autonomous

**Comment by prattmic** [comment]
Hi Matt,

Can you clarify which endpoints don't seem to require a cookie and which
client you are using?  Almost every endpoint (e.g., /api/targets,
/api/telemetry) should return a 403 error if no cookie is sent.

However, if you are using the provided sample client in this repo
(client/interop/), note that it does automatically handle the cookie for
you. When the Client object is created, a login request is made and the
returned cookie is sent on all subsequent requests.

**Comment by Codexer** [comment]
We have extended the sample client in the repo. Also, we have only tested the /api/telemetry/ endpoints. 

If the client does handle the login requests for us, then I think we are safe with our current client. For curiosity's sake, where in the code does the server create and send the login cookie? (I don't have much experience with Django, so this might be useful sometime in the future.)

Thank you for your response,
- Matt T / RU Autonomous

**Comment by prattmic** [comment]
In the client, we [use](https://github.com/auvsi-suas/interop/blob/master/client/interop/client.py#L41) a [requests.Session](http://docs.python-requests.org/en/master/user/advanced/#session-objects), which automatically persists cookies from the login request.

I agree this isn't very clear; I will leave this issue open and update the docs to make this clear.

On the server side, the `/api/login` endpoint is handled [here](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/views/login.py). (Find all of them [here](https://github.com/auvsi-suas/interop/blob/master/server/auvsi_suas/views/urls.py)). It is mostly a wrapper around standard [Django authentication](https://docs.djangoproject.com/en/1.8/topics/auth/default/#auth-web-requests).
