### ISSUE TITLE
Cleaning database after flight

### ISSUE THREAD

**Issue by DarkmatterVale** [auvsi-suas/interop#97]
Hi,

How are we supposed to clean the database after our flights? I tried using the the commands:

```
$ cd ~/interop/server
$ source venv/bin/activate
$ python manage.py flush
$ python manage.py syncdb
```

Running the above code causes issues and does not properly reset the database. Below are the logs I gathered from running the test script.

http://paste.ubuntu.com/15739054/

**Comment by prattmic** [comment]
The client tests expect some test data to be installed in the database.

`python manage.py loaddata fixtures/test_fixture.yaml`

**Comment by idogreenfeld** [comment]
is there a away of deleting only the UAS telemetrys?

**Comment by legonigel** [comment]
@idogreenfeld  one way you could delete all the UAS telemetry is through the Django shell.

The following code opens the Django shell, import the models, then deletes all the UasTelemtry Objects:
```
python manage.py shell
import auvsi_suas.models
auvsi_suas.models.UasTelemetry.objects.all().remove()
```
